In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
api_url_names = "https://motenmedborgarportal.malmo.se/api/err/v1.0/representatives?committeeId=909&pageSize=9999"
api_response_names = requests.get(api_url_names)

print(api_response_names.status_code)
politician_names = api_response_names.json()

politician_names

200

{'Items': [{'Id': 'ae093f9c-679c-4e6a-a27c-16c2ca0cea19',
   'Name': 'Albin Schyllert',
   'Email': 'albin.schyllert@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/5c700ec2-08b2-45f0-9343-ff8733903e4ajpg'},
  {'Id': '9891bac6-6ea1-447e-979d-955146c3aa71',
   'Name': 'Amanda Johannesson',
   'Email': 'amanda.johannesson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/d5480762-6cc9-4e38-9807-a5889aa340eejpg'},
  {'Id': '59b723e4-235f-4170-bd52-33ab369da4a2',
   'Name': 'Amani Loubani',
   'Email': 'amani.loubani@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/d361bd8c-4d77-4d0d-910a-56e069a3d606jpg'},
  {'Id': '2f80a096-78a0-40b9-8557-15c09581116f',
   'Name': 'Ana Maria Stuparich-Clementi',
   'Email': 'anamaria.stuparich-clementi@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/ceb3e3c1-8eaa-450b-b92c-2b2579f2789ejpg'},
  {'Id': '05bff02c-6fe0-48dc-83db-0f720e669bca',
   'Name': 'Anders Andersson',
   'Email': 'anders.g.andersson@malmo.se',
   'WorkPhone': ' 040-34 10 17',
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/c1beb3eb-9ee5-4ee6-8412-e2a73d28dcfdjpg'},
  {'Id': '821082aa-ce67-4052-a601-f4170f359150',
   'Name': 'Anders Nilsson',
   'Email': 'anders.s.nilsson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': '0708743993',
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/ef121a0c-5169-4fc9-a035-f07451f10ffajpg'},
  {'Id': '8cca2a82-203b-4130-8cdc-449d5ac7d725',
   'Name': 'Anders Olin',
   'Email': 'Anders.Olin@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/d3295f7a-d2a0-4ca9-a1a5-f0b53d0f7ec6jpg'},
  {'Id': '257a47db-e3c1-485e-81c3-dee7e47f53b1',
   'Name': 'Anders Pripp',
   'Email': 'Anders.Pripp@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/da8b2ac9-7991-4f62-afcf-c1d0ccca695ajpg'},
  {'Id': '2647b31c-a2f2-427f-91a5-313ef2cd8645',
   'Name': 'Anders Rubin',
   'Email': 'anders.rubin@malmo.se',
   'WorkPhone': '040-341009',
   'PersonalPhone': '0706362677',
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/f356ac5f-0108-4b78-9536-6e90ab856284jpg'},
  {'Id': '97faa028-2eea-4b7f-9226-60172e065e35',
   'Name': 'Anders Skans',
   'Email': 'anders.skans@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/3163d697-f528-46c2-982f-95abe11b6ee9jpg'},
  {'Id': 'd46cb654-15f6-43dc-bd6b-6677a34f5e62',
   'Name': 'Andréas Schönström',
   'Email': 'Andreas.Schonstrom@malmo.se',
   'WorkPhone': '040-34 10 16',
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/f2452d0f-04c0-44ee-a0ef-896c3c704a25jpg'},
  {'Id': '174aab56-baab-4af1-b6d4-f9339695d8e2',
   'Name': 'Anfal Mahdi',
   'Email': 'anfal.mahdi@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/909e6c0c-c58e-4eba-8fad-c76c621c9d05jpg'},
  {'Id': 'de8eddc7-97c9-4f3d-91b1-21baa9210ac2',
   'Name': 'Anja Nordberg Sonesson',
   'Email': 'anja.nordbergsonesson@malmo.se',
   'WorkPhone': '0703739042',
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/9d7c39df-338c-4d56-81c6-53ce8987699djpg'},
  {'Id': '9ead4156-bc4e-46ba-893a-3d641cbe0bd1',
   'Name': 'Anna Ljunggren',
   'Email': 'anna.ljunggren@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'ce225fef-658b-4da0-9700-2d456d3bcc93',
    'Name': 'Miljöpartiet De Gröna'},
   'ImageLink': '/sv/documents/ae979306-4f0a-44b1-9687-c13cb4bcf31djpg'},
  {'Id': 'ff30a6ce-9f69-4a81-a5e1-4c0112e5d6fc',
   'Name': 'Anton Sauer',
   'Email': 'anton.sauer@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '80fc76af-01bd-4c27-9e4d-90900af2106f',
    'Name': 'Centerpartiet'},
   'ImageLink': '/sv/documents/a9889228-0957-4998-a80a-58dce28cb8dfjpg'},
  {'Id': '5244b237-0261-4979-88f1-c445450e30ed',
   'Name': 'Arwin Sohrabi Nejad',
   'Email': 'Arwin.Sohrabi@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/182d64a1-65a1-4bfc-a5ad-a997ab2e2325jpg'},
  {'Id': '132fb10d-5c41-4566-bd02-82a912d1aa73',
   'Name': 'Bengt-Göran Svensson',
   'Email': 'bengt-goran.svensson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/818c04b2-3834-4b94-b970-98f16dfd9ef8jpg'},
  {'Id': 'bc91342f-2be9-4b07-acb5-8a4d9d1b1e6e',
   'Name': 'Birgit Hansson',
   'Email': 'birgit.hansson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/b2d03f55-1aa6-405f-a5f9-89a6200b40b4jpg'},
  {'Id': 'ad2fe56d-40a4-4750-a693-b6147a316280',
   'Name': 'Birgitta Ehlin',
   'Email': 'birgitta.ehlin@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/311121ce-af08-4fd7-a342-4683158ffee5jpg'},
  {'Id': 'a3494799-c3e6-4c69-a39b-7a23a863ef85',
   'Name': 'Björn Gudmundsson',
   'Email': 'Bjorn.Gudmundsson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': '0706313134',
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/b37bc4b8-ae7f-49db-93bd-cb1736fb5db4jpg'},
  {'Id': '9c88fa86-7429-4454-9b95-ce77032bcbf6',
   'Name': 'Boel Pettersson',
   'Email': 'boel.pettersson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/d622d012-c584-4206-a6af-fc8c28140566jpg'},
  {'Id': '212b74c5-1690-4295-9160-7b6e1d42a288',
   'Name': 'Carina Nilsson',
   'Email': 'carina.nilsson.ks@malmo.se',
   'WorkPhone': '040-34 10 27',
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/7b8d15e0-4b93-4c94-9adf-1dc8980cee20jpg'},
  {'Id': '63f5553e-058f-4a00-9a16-f6cda504ca43',
   'Name': 'Carin Gustafsson',
   'Email': 'carin.gustafsson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/861af505-0d0a-4acd-9593-3c74901c9d5djpg'},
  {'Id': '976de9a6-c98f-4b61-89eb-af5eb4691a14',
   'Name': 'Danica Srnic',
   'Email': 'Danica.Srnic@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': None},
  {'Id': '65dbc052-da82-4448-adac-e33aa90d385f',
   'Name': 'Darko Simic',
   'Email': 'darko.simic@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/bc06f389-acc2-450d-af7c-a71d90520f7bjpg'},
  {'Id': '1599d958-ffd2-4654-a0bf-f9cb0043e3f9',
   'Name': 'Dündar Güngör',
   'Email': 'Dundar.Gungor@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/31a716ec-8ea7-4bcf-b464-dca4ee942694jpg'},
  {'Id': 'a4f08df5-06eb-41ab-9cab-e2a29d2c4468',
   'Name': 'Erik Hammarström',
   'Email': 'erik.hammarstrom@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'ce225fef-658b-4da0-9700-2d456d3bcc93',
    'Name': 'Miljöpartiet De Gröna'},
   'ImageLink': '/sv/documents/bead2d7f-0973-47d5-af5e-b1c28c2e3a1djpg'},
  {'Id': '5256575b-0700-4f75-adf9-0148f08670f3',
   'Name': 'Eva Bertz',
   'Email': 'ewa.bertz@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '9e4e32a0-fd7a-4332-8821-ce16ffe04e29',
    'Name': 'Liberalerna'},
   'ImageLink': '/sv/documents/4abf38a3-7d00-45ab-8608-620bb16165d3jpg'},
  {'Id': '992e9c87-2f18-4a8a-9588-d39b84c54324',
   'Name': 'Eva Hallén',
   'Email': 'eva.hallen@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/1f14266d-c3db-4c1c-8555-9edcf46f640cjpg'},
  {'Id': '31b57dd2-c1d5-4be6-8842-26f21b6d909b',
   'Name': 'Ewa Langerbeck',
   'Email': 'ewa.langerbeck@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '80fc76af-01bd-4c27-9e4d-90900af2106f',
    'Name': 'Centerpartiet'},
   'ImageLink': '/sv/documents/46a8ef9b-f020-4e56-857b-cb157a69a0e5jpg'},
  {'Id': 'c1d0c0f3-cc2e-477f-8f39-c34fec13e45a',
   'Name': 'Farishta Sulaiman',
   'Email': 'farishta.sulaiman@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/22de16e1-f562-45a8-a14f-b7f15617386ejpg'},
  {'Id': 'c99a63ce-c119-4f69-91cd-351133aab3cc',
   'Name': 'Frida Trollmyr',
   'Email': 'frida.trollmyr@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/98b49406-dab9-45c6-b6d6-950ef7c8cb2djpg'},
  {'Id': '96a55325-9fd0-4dab-b775-93326d51c9e9',
   'Name': 'Håkan Ask',
   'Email': 'hakan.ask@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/e823a2da-4cab-4cf7-b1f9-01f9b484f3dajpg'},
  {'Id': '98b835ab-0a26-44e6-a111-3ca3ad20055d',
   'Name': 'Håkan Fäldt',
   'Email': 'Hakan.Faldt@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/84a527a4-a152-402b-86ac-97e4b6bde76bjpg'},
  {'Id': 'e4ed8408-250c-4a1c-9b64-4e3d9c66073c',
   'Name': 'Hanna Sandberg',
   'Email': 'hanna.sandberg@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/900cc862-78d3-42ae-852b-944ad85198dbjpg'},
  {'Id': 'feb822f1-6ff0-4f7d-b9ef-501ba28554ad',
   'Name': 'Haqvin Svensson',
   'Email': 'haqvin.svensson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/8eef00b9-7545-442f-bba9-b3a3e6c1198djpg'},
  {'Id': 'a12f43a0-6e65-47df-bfc0-9eca1b1a31c3',
   'Name': 'Hasse Hajar',
   'Email': 'hasse.hajar@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/dc931c6c-7278-4c92-aa88-b2f4676f5beajpg'},
  {'Id': '6def4f89-9052-4540-a78f-0c154a5d1dc2',
   'Name': 'Helena Grahn',
   'Email': 'Helena.Grahn@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/32110196-8e63-4b86-97f6-76641e24256cjpg'},
  {'Id': '0500f3ac-fe5f-4abf-ad3d-d93c34b46314',
   'Name': 'Helena Nanne',
   'Email': 'Helena.Nanne@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/be2f64f4-f0f3-4b17-a51f-e74de140fc93jpg'},
  {'Id': '4f2849fd-daa6-4924-8255-649cd893ae12',
   'Name': 'Henning Süssner Rubin',
   'Email': '',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': None},
  {'Id': '3b584612-f5c6-4325-9229-b6131291ba0f',
   'Name': 'Ingrid Gunnarson',
   'Email': 'ingridanna-l.gunnarson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/a769e649-cfe4-4422-be29-0059861bcc65jpg'},
  {'Id': '43d4a72b-9869-4903-916b-851482e6a85f',
   'Name': 'Jacqueline Maly',
   'Email': 'jacquelineisabell.maly@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/39cf12c7-2873-46a7-aa58-dd3b529c8831jpg'},
  {'Id': '8a33c931-c809-4c80-8aa8-d78759c8da44',
   'Name': 'Janne Grönholm',
   'Email': 'janne.gronholm@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'ce225fef-658b-4da0-9700-2d456d3bcc93',
    'Name': 'Miljöpartiet De Gröna'},
   'ImageLink': '/sv/documents/ae61558a-aa4a-46ac-b620-d39285d2e31ajpg'},
  {'Id': '4df6dbeb-141e-465b-95c3-29c2d2bb06da',
   'Name': 'Jan Olsson',
   'Email': 'Jan.E.Olsson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/cd01c618-b144-4624-a9d6-bcf2c8871028jpg'},
  {'Id': '9e578f96-e7b8-4da4-bd7c-56421dbdd0c8',
   'Name': 'Jenny Bengtsson',
   'Email': 'jenny.bengtsson3@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/cb214c6a-d9cb-44db-9234-40272b97a295jpg'},
  {'Id': 'f9910041-78d5-4690-8f7f-7e4107259d58',
   'Name': 'Joel Laguna Ascacivar',
   'Email': 'Joel.Laguna@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '9e4e32a0-fd7a-4332-8821-ce16ffe04e29',
    'Name': 'Liberalerna'},
   'ImageLink': '/sv/documents/568486e2-103f-46da-8f12-691a4337dd13jpg'},
  {'Id': 'c6b49b0f-6954-4e24-9a01-0407399428e1',
   'Name': 'John Eklöf',
   'Email': 'John.Eklof@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/ee69404b-23e5-4237-a731-d8eb24462f6fjpg'},
  {'Id': 'a4591f57-dd28-410b-bdf2-64f3de9c69bf',
   'Name': 'John Roslund',
   'Email': 'john.roslund@malmo.se',
   'WorkPhone': '0709162312',
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'b6ad83ab-710a-48c6-967b-0ff17164d27c',
    'Name': 'Politiskt obunden'},
   'ImageLink': '/sv/documents/2c8a5b42-c90d-4c16-8715-3fd7ba6a0bd5jpg'},
  {'Id': 'd61429d6-a0a1-4ec4-a35c-a285757ed2dd',
   'Name': 'Jörgen Grubb',
   'Email': 'Jorgen.Grubb@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/21ade062-8bc0-4bfe-8685-8f4649b2ef7ejpg'},
  {'Id': '93ea9222-a9b4-4c9b-94a5-09fe67676ca6',
   'Name': 'Juan-Tadeo Espitia',
   'Email': 'Juan.Espitia@malmo.se',
   'WorkPhone': ' 0708-78 05 26',
   'PersonalPhone': '076-945 56 69',
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/ec11d4ca-12ac-4b9c-adb7-62ffe50efc44jpg'},
  {'Id': 'c754e6e9-8735-429b-b89b-c8e1e41f87dc',
   'Name': 'Katrin Stjernfeldt Jammeh',
   'Email': 'katrin.stjernfeldt-jammeh@malmo.se',
   'WorkPhone': '040-341014',
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'a7e181f6-1b24-43ed-804a-97a437df2413',
    'Name': 'Arbetarepartiet Socialdemokraterna'},
   'ImageLink': '/sv/documents/43c2e200-412d-46b8-b8a7-f58b1948bbbbjpg'},
  {'Id': 'd4960123-e994-4975-9c49-5b6c3cbe6c92',
   'Name': 'Kay Wictorin',
   'Email': 'kay.wictorin@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '80fc76af-01bd-4c27-9e4d-90900af2106f',
    'Name': 'Centerpartiet'},
   'ImageLink': '/sv/documents/d535f92e-df81-42b4-8c61-1e00e64677edjpg'},
  {'Id': '6d94772b-4428-4ade-9fdf-081045385c06',
   'Name': 'Kerstin Håkansson',
   'Email': 'kerstin.hakansson@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/2bd27460-442d-4267-abb1-52ba9addf525jpg'},
  {'Id': '80e4b2ce-0a83-40d8-b5f1-ed1808f3c40b',
   'Name': 'Lars-Johan Hallgren',
   'Email': 'lars-johan.hallgren@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},
   'ImageLink': '/sv/documents/7566fd06-5b2c-4dd2-897f-b865fc612a53jpg'},
  {'Id': '8dc93c78-721d-4fd9-9e49-fc3b2c805f3a',
   'Name': 'Linda Eklund',
   'Email': 'linda.eklund@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '9e4e32a0-fd7a-4332-8821-ce16ffe04e29',
    'Name': 'Liberalerna'},
   'ImageLink': '/sv/documents/2729f17e-946d-4c67-bb74-87c11d27c22cjpg'},
  {'Id': '16dd7e81-9c4e-4be9-bfc4-795434d2fd05',
   'Name': 'Linda Obiedzinski',
   'Email': 'linda.obiedzinski@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': ' 0708-519 951',
   'PoliticalParty': {'Id': 'b06f9b2c-b363-456a-bb77-311620622c09',
    'Name': 'Moderaterna'},
   'ImageLink': '/sv/documents/d505de03-d0bc-4e78-8bdc-db7deba257efjpg'},
  {'Id': 'aa9642d1-0341-4cbd-b169-3db7d14f77af',
   'Name': 'Lisa Stolpe',
   'Email': 'Lisa.Stolpe@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': 'd79928a2-19c1-4a88-a8aa-2c3ddf9e1820',
    'Name': 'Vänsterpartiet'},
   'ImageLink': '/sv/documents/1aa843f7-1d88-494b-ae36-6c68e0c77da8jpg'},
  {'Id': 'daf48514-1b99-4c8e-b517-f99680c2af40',
   'Name': 'Lisbeth Persson Ekström',
   'Email': 'Lisbeth.Persson-Ekstrom@malmo.se',
   'WorkPhone': None,
   'PersonalPhone': None,
   'PoliticalParty': {'Id': '10dee4f6-991f-4f97-87bb-f59f8e18476f',
    'Name': 'Sverigedemokraterna'},

In [3]:
politician_names_df = pd.json_normalize(
    politician_names["Items"],
    sep="_"
)

politician_names_df = politician_names_df.rename(columns={
    "Id": "RepresentativeId",
    "PoliticalParty_Name": "PoliticalParty"
})

politician_names_df = politician_names_df[
    [
        "Name",
        "RepresentativeId",
        "PoliticalParty",
        "PoliticalParty_Id"
    ]
]

display(politician_names_df.head())
print(len(politician_names_df))

,Name,RepresentativeId,PoliticalParty,PoliticalParty_Id
0,Albin Schyllert,ae093f9c-679c-4e6a-a27c-16c2ca0cea19,Moderaterna,b06f9b2c-b363-456a-bb77-311620622c09
1,Amanda Johannesson,9891bac6-6ea1-447e-979d-955146c3aa71,Arbetarepartiet Socialdemokraterna,a7e181f6-1b24-43ed-804a-97a437df2413
2,Amani Loubani,59b723e4-235f-4170-bd52-33ab369da4a2,Arbetarepartiet Socialdemokraterna,a7e181f6-1b24-43ed-804a-97a437df2413
3,Ana Maria Stuparich-Clementi,2f80a096-78a0-40b9-8557-15c09581116f,Vänsterpartiet,d79928a2-19c1-4a88-a8aa-2c3ddf9e1820
4,Anders Andersson,05bff02c-6fe0-48dc-83db-0f720e669bca,Vänsterpartiet,d79928a2-19c1-4a88-a8aa-2c3ddf9e1820

93

In [4]:
api_url_roles = "https://motenmedborgarportal.malmo.se/api/err/v1.0/committees/909/assignments?termOfOfficeId=019511cb-0cc8-4b34-ba97-75ca4fb5ef65"
api_response_roles = requests.get(api_url_roles)

print(api_response_roles.status_code)
politician_roles = api_response_roles.json()
politician_roles

200

[{'RepresentativeId': 'a2789854-37cf-4cc2-8520-81a5da8e4c54',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 78,
  'State': 'Current'},
 {'RepresentativeId': '821082aa-ce67-4052-a601-f4170f359150',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 63,
  'State': 'Current'},
 {'RepresentativeId': 'd1991c1f-3062-4da9-830d-fa4ac7548468',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 70,
  'State': 'Current'},
 {'RepresentativeId': 'cd4bf158-4e69-4ce5-921c-ebfd5159599b',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 69,
  'State': 'Current'},
 {'RepresentativeId': 'bc91342f-2be9-4b07-acb5-8a4d9d1b1e6e',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 68,
  'State': 'Current'},
 {'RepresentativeId': 'e4ed8408-250c-4a1c-9b64-4e3d9c66073c',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 50,
  'State': 'Current'},
 {'RepresentativeId': '4f2849fd-daa6-4924-8255-649cd893ae12',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 88,
  'State': 'Current'},
 {'RepresentativeId': '7f4f8664-d875-4d98-b3b8-a606f1c43646',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 65,
  'State': 'Current'},
 {'RepresentativeId': '9891bac6-6ea1-447e-979d-955146c3aa71',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 66,
  'State': 'Current'},
 {'RepresentativeId': 'afb5ceef-251c-4b9c-a09e-f640a0e5f272',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 67,
  'State': 'Current'},
 {'RepresentativeId': 'ac638b47-78fa-4e8d-a6e5-50948d9488e2',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 62,
  'State': 'Current'},
 {'RepresentativeId': '23f30630-a794-4fa6-9993-551b9f759359',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 64,
  'State': 'Current'},
 {'RepresentativeId': 'a12f43a0-6e65-47df-bfc0-9eca1b1a31c3',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-09-07',
  'DateTo': '2026-10-14',
  'Number': 71,
  'State': 'Current'},
 {'RepresentativeId': 'ad2fe56d-40a4-4750-a693-b6147a316280',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 85,
  'State': 'Current'},
 {'RepresentativeId': '2f80a096-78a0-40b9-8557-15c09581116f',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 87,
  'State': 'Current'},
 {'RepresentativeId': '10e59e37-c218-45d5-be5c-93a72e35037b',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 76,
  'State': 'Current'},
 {'RepresentativeId': '6d94772b-4428-4ade-9fdf-081045385c06',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 86,
  'State': 'Current'},
 {'RepresentativeId': '976de9a6-c98f-4b61-89eb-af5eb4691a14',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 77,
  'State': 'Current'},
 {'RepresentativeId': '4bf9c9e6-cc99-4058-9570-5597789e0c92',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 84,
  'State': 'Current'},
 {'RepresentativeId': 'b26a11ac-7c72-4a1b-ab2f-3b915bcfa34b',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2026-08-28',
  'DateTo': '2026-10-14',
  'Number': 75,
  'State': 'Current'},
 {'RepresentativeId': '101c67c4-afed-41dd-990d-498e9ff440ba',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2025-09-02',
  'DateTo': '2026-10-14',
  'Number': 13,
  'State': 'Current'},
 {'RepresentativeId': '3b584612-f5c6-4325-9229-b6131291ba0f',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-09-02',
  'DateTo': '2026-10-14',
  'Number': 72,
  'State': 'Current'},
 {'RepresentativeId': '65dbc052-da82-4448-adac-e33aa90d385f',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-09-02',
  'DateTo': '2026-10-14',
  'Number': 74,
  'State': 'Current'},
 {'RepresentativeId': 'ee266fb0-82e2-4505-837f-7efddde08a1f',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-09-02',
  'DateTo': '2026-10-14',
  'Number': 73,
  'State': 'Current'},
 {'RepresentativeId': 'd4960123-e994-4975-9c49-5b6c3cbe6c92',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2025-06-05',
  'DateTo': '2026-10-14',
  'Number': 15,
  'State': 'Current'},
 {'RepresentativeId': '34331c59-4650-4ea2-ba8a-2c216e89f9a1',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-06-05',
  'DateTo': '2026-10-14',
  'Number': 93,
  'State': 'Current'},
 {'RepresentativeId': '31b57dd2-c1d5-4be6-8842-26f21b6d909b',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-06-05',
  'DateTo': '2026-10-14',
  'Number': 94,
  'State': 'Current'},
 {'RepresentativeId': 'a4f08df5-06eb-41ab-9cab-e2a29d2c4468',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-02-03',
  'DateTo': '2026-10-14',
  'Number': 90,
  'State': 'Current'},
 {'RepresentativeId': '9ead4156-bc4e-46ba-893a-3d641cbe0bd1',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2025-02-03',
  'DateTo': '2026-10-14',
  'Number': 89,
  'State': 'Current'},
 {'RepresentativeId': 'aa9642d1-0341-4cbd-b169-3db7d14f77af',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2024-11-05',
  'DateTo': '2026-10-14',
  'Number': 45,
  'State': 'Current'},
 {'RepresentativeId': '38798a0f-cdc8-4e69-ac55-95097335e400',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2024-11-05',
  'DateTo': '2026-10-14',
  'Number': 4,
  'State': 'Current'},
 {'RepresentativeId': 'de1dea17-eb11-4ad9-9e82-43ad482d4826',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2022-12-30',
  'DateTo': '2026-10-14',
  'Number': 83,
  'State': 'Current'},
 {'RepresentativeId': 'feb822f1-6ff0-4f7d-b9ef-501ba28554ad',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2022-12-02',
  'DateTo': '2026-10-14',
  'Number': 41,
  'State': 'Current'},
 {'RepresentativeId': '43a61c52-428e-4e66-a61b-843a42f28ea5',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2022-12-02',
  'DateTo': '2026-10-14',
  'Number': 46,
  'State': 'Current'},
 {'RepresentativeId': '992e9c87-2f18-4a8a-9588-d39b84c54324',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2022-11-18',
  'DateTo': '2026-10-14',
  'Number': 82,
  'State': 'Current'},
 {'RepresentativeId': '197d2cd3-5ce3-4b4a-853d-2a4032f7388a',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2022-11-18',
  'DateTo': '2026-10-14',
  'Number': 81,
  'State': 'Current'},
 {'RepresentativeId': '5256575b-0700-4f75-adf9-0148f08670f3',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2022-11-17',
  'DateTo': '2026-10-14',
  'Number': 91,
  'State': 'Current'},
 {'RepresentativeId': 'f9910041-78d5-4690-8f7f-7e4107259d58',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ersättare',
  'DateFrom': '2022-11-17',
  'DateTo': '2026-10-14',
  'Number': 92,
  'State': 'Current'},
 {'RepresentativeId': '5244b237-0261-4979-88f1-c445450e30ed',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2022-10-15',
  'DateTo': '2026-10-14',
  'Number': 48,
  'State': 'Current'},
 {'RepresentativeId': 'de8eddc7-97c9-4f3d-91b1-21baa9210ac2',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Andre vice ordförande',
  'DateFrom': '2022-10-15',
  'DateTo': '2026-10-14',
  'Number': 18,
  'State': 'Current'},
 {'RepresentativeId': 'a4cecad6-62f7-4fde-b248-87cea7325fda',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',
   'ZipCode': '211 35',
   'City': 'Malmö',
   'PhoneNumber': '040-34 10 25',
   'Email': 'kansli.kf@malmo.se',
   'Fax': '',
   'WebsiteLink': None,
   'Address': 'Kalendegatan 1'},
  'Role': 'Ledamot',
  'DateFrom': '2022-10-15',
  'DateTo': '2026-10-14',
  'Number': 9,
  'State': 'Current'},
 {'RepresentativeId': '4f529682-108f-41b9-b55a-e2cf9749bb15',
  'Committee': {'Id': 909,
   'Name': 'Kommunfullmäktige',
   'ShortName': '',
   'Link': 'committees/kommunfullmaktige',

In [5]:
politician_roles_df = pd.json_normalize(
    politician_roles,
    sep="_"
)


politician_roles_df = politician_roles_df[
    [
        "RepresentativeId",
        "Role",
        "DateFrom",
        "DateTo",
        "Number",
        "State",
        "Committee_Name"
    ]
]

display(politician_roles_df.head())
print(len(politician_roles_df))

,RepresentativeId,Role,DateFrom,DateTo,Number,State,Committee_Name
0,a2789854-37cf-4cc2-8520-81a5da8e4c54,Ersättare,2026-09-07,2026-10-14,78,Current,Kommunfullmäktige
1,821082aa-ce67-4052-a601-f4170f359150,Ersättare,2026-09-07,2026-10-14,63,Current,Kommunfullmäktige
2,d1991c1f-3062-4da9-830d-fa4ac7548468,Ersättare,2026-09-07,2026-10-14,70,Current,Kommunfullmäktige
3,cd4bf158-4e69-4ce5-921c-ebfd5159599b,Ersättare,2026-09-07,2026-10-14,69,Current,Kommunfullmäktige
4,bc91342f-2be9-4b07-acb5-8a4d9d1b1e6e,Ersättare,2026-09-07,2026-10-14,68,Current,Kommunfullmäktige

93

In [6]:
politicians_df = politician_names_df.merge(
    politician_roles_df,
    on="RepresentativeId",
    how="left"
)

print(len(politicians_df))
politicians_df.head()

93

,Name,RepresentativeId,PoliticalParty,PoliticalParty_Id,Role,DateFrom,DateTo,Number,State,Committee_Name
0,Albin Schyllert,ae093f9c-679c-4e6a-a27c-16c2ca0cea19,Moderaterna,b06f9b2c-b363-456a-bb77-311620622c09,Ledamot,2022-10-15,2026-10-14,61,Current,Kommunfullmäktige
1,Amanda Johannesson,9891bac6-6ea1-447e-979d-955146c3aa71,Arbetarepartiet Socialdemokraterna,a7e181f6-1b24-43ed-804a-97a437df2413,Ersättare,2026-09-07,2026-10-14,66,Current,Kommunfullmäktige
2,Amani Loubani,59b723e4-235f-4170-bd52-33ab369da4a2,Arbetarepartiet Socialdemokraterna,a7e181f6-1b24-43ed-804a-97a437df2413,Ledamot,2022-10-15,2026-10-14,26,Current,Kommunfullmäktige
3,Ana Maria Stuparich-Clementi,2f80a096-78a0-40b9-8557-15c09581116f,Vänsterpartiet,d79928a2-19c1-4a88-a8aa-2c3ddf9e1820,Ersättare,2026-08-28,2026-10-14,87,Current,Kommunfullmäktige
4,Anders Andersson,05bff02c-6fe0-48dc-83db-0f720e669bca,Vänsterpartiet,d79928a2-19c1-4a88-a8aa-2c3ddf9e1820,Ledamot,2022-10-15,2026-10-14,57,Current,Kommunfullmäktige

In [7]:
url_meetings = "https://motenmedborgarportal.malmo.se/committees/kommunfullmaktige#committeesRecentContent"
response_meetings = requests.get(url_meetings)

soup = BeautifulSoup(response_meetings.text, "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html class="no-js" lang="sv">
 <head>
  <meta charset="utf-8"/>
  <meta content="Kommunfullmäktige" name="description"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,height=device-height, initial-scale=1" name="viewport"/>
  <title>
   Kommunfullmäktige | MeetingPlus [sv]
  </title>
  <link href="/fonts/local-fonts.less" rel="stylesheet" type="text/css"/>
  <link href="/bundles/web-app-styles.css?v=Vmgkl8JuQVcBIDNDg3Js4QVVIA3R9OQxrF0AoR_4bVg1" rel="stylesheet"/>
  <script src="/bundles/libraries.js?v=c6pRkBWBvu7iGhyF15_rDTBj4dsXU3IDLUaGb6CCnhE1">
  </script>
  <script>
   cssVars({ onlyLegacy: true });
  </script>
  <script src="/bundles/accessibleCheckboxControl.js?v=BeKO6qIzC1enkD3RwwKHDChAhTm1YJDm0AONmu6kq_I1">
  </script>
  <script>
   document.meetingsPlusUser = "anonymous";
        document.isMobileClient = false;
        document.acceptLanguageHeaderValue = "sv";

        function getAntiForgeryHeader() {
            var tokenKey = "__RequestVerificationToken";
            var antiForgeryToken = "1reK9WavxKQJPsPjaQzx1eJX1AGJEGrm-7Z9e5Yw_pl0uIWBsfXujJ36SrjUhkZ9q-rHjXl0lbbgBNZfgIsltIAKpW41";
            var headers = {};
            headers[tokenKey] = antiForgeryToken;
            return headers;
        }



        document.addEventListener("DOMContentLoaded", function () {
            var helpLinks = document.querySelectorAll("a.help-link[data-no-url='true']");
            if (helpLinks.length) {
                helpLinks.forEach(function (hl) {
                    hl.addEventListener("click", function (e) {
                        e.preventDefault();
                        alert("Ingen URL har angivits för hjälpfunktionen, vänligen kontakta administratör.");
                    });
                });
            }
        });
  </script>
  <script>
   NS_CSM_td=6471528;NS_CSM_pd=275116665;NS_CSM_u="/clm10";NS_CSM_col="AAAAAAUsoHLtwzi/bo7v/yRHlKn2/Eq9N09TGCeLbOyj0V69wVsTFdsc2i/k0XKGz9mWdwLRPD/wM7MQ5D2ZL8q7lu+1";
  </script>
  <script type="text/javascript">
   function sendTimingInfoInit(){setTimeout(sendTimingInfo,0)}function sendTimingInfo(){var wp=window.performance;if(wp){var c1,c2,t;c1=wp.timing;if(c1){var cm={};cm.ns=c1.navigationStart;if((t=c1.unloadEventStart)>0)cm.us=t;if((t=c1.unloadEventEnd)>0)cm.ue=t;if((t=c1.redirectStart)>0)cm.rs=t;if((t=c1.redirectEnd)>0)cm.re=t;cm.fs=c1.fetchStart;cm.dls=c1.domainLookupStart;cm.dle=c1.domainLookupEnd;cm.cs=c1.connectStart;cm.ce=c1.connectEnd;if((t=c1.secureConnectionStart)>0)cm.scs=t;cm.rqs=c1.requestStart;cm.rss=c1.responseStart;cm.rse=c1.responseEnd;cm.dl=c1.domLoading;cm.di=c1.domInteractive;cm.dcls=c1.domContentLoadedEventStart;cm.dcle=c1.domContentLoadedEventEnd;cm.dc=c1.domComplete;if((t=c1.loadEventStart)>0)cm.ls=t;if((t=c1.loadEventEnd)>0)cm.le=t;cm.tid=NS_CSM_td;cm.pid=NS_CSM_pd;cm.ac=NS_CSM_col;var xhttp=new XMLHttpRequest();if(xhttp){var JSON=JSON||{};JSON.stringify=JSON.stringify||function(ob){var t=typeof(ob);if(t!="object"||ob===null){if(t=="string")ob='"'+ob+'"';return String(ob);}else{var n,v,json=[],arr=(ob&&ob.constructor==Array);for(n in ob){v=ob[n];t=typeof(v);if(t=="string")v='"'+v+'"';else if(t=="object"&&v!==null)v=JSON.stringify(v);json.push((arr?"":'"'+n+'":')+String(v));}return(arr?"[":"{")+String(json)+(arr?"]":"}");}};xhttp.open("POST",NS_CSM_u,true);xhttp.send(JSON.stringify(cm));}}}}if(window.addEventListener)window.addEventListener("load",sendTimingInfoInit,false);else if(window.attachEvent)window.attachEvent("onload",sendTimingInfoInit);else window.onload=sendTimingInfoInit;
  </script>
 </head>
 <body class="committee">
  <a href="#main" id="skipNavigation">
   Hoppa över navigering
  </a>
  <div class="site-wrap">
   <header class="header no-print">
    <div class="container-fluid wrapper">
     <div class="row">
      <div class="col-md-4 w-auto">
       <a href="https://motenmedborgarportal.malmo.se:443/" id="mainLogoLink" role="link">
        <img alt="Malmö Stad, Medborgarportal start" class="main-logo"/>
       </a>
      </div>
      <div class="col-md-4 full-text-search-container">
       <div class="search-global" role="search">
        <input aria-labelledby="full-text-search-label" id="full-text-search" placeholder=" " type="search"/>
        <label for="full-text-search" id="full-text-search-label">
         Sök
        </label>
       </div>
      </div>
      <div class="col-md-4 w-auto">
       <div class="user unlogged">
        <a class="log-link" href="https://motenmedborgarportal.malmo.se/AuthorizationServer/Account/login?client_id=IWP123&amp;client_secret=IWP123&amp;redirect_uri=https%3a%2f%2fmotenmedborgarportal.malmo.se%2fcommittees%2fkommunfullmaktige&amp;language=sv" role="link">
         Logga in
         <span class="log-icon">
         </span>
        </a>
       </div>
      </div>
     </div>
    </div>
    <div class="main-nav">
     <nav aria-label="Huvudmeny" class="nav-menu site-nav-menu">
      <button aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" id="DropDownButton" type="button">
       Nämnder &amp; Styrelser
      </button>
      <ul class="dropdown-menu">
       <li class="">
        <a aria-current="" href="/overview" id="PageLink_overview">
         Översikt
        </a>
       </li>
       <li class="active">
        <a aria-current="page" href="/committees" id="PageLink_committees">
         Nämnder &amp; Styrelser
        </a>
       </li>
       <li class="">
        <a aria-current="" href="/representatives" id="PageLink_representatives">
         Förtroendevalda
        </a>
       </li>
       <li class="">
        <a aria-current="" href="/political-parties" id="PageLink_political-parties">
         Politiska partier
        </a>
       </li>
       <li class="">
        <a aria-current="" href="/digital-bulletin-board" id="PageLink_digital-bulletin-board">
         ANSLAGSTAVLA
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </header>
   <main class="main" id="main">
    <div class="container-fluid wrapper">
     <div class="row">
      <div class="col-12">
       <form action="./kommunfullmaktige" id="ctl00" method="post" novalidate="novalidate">
        <input id="__VIEWSTATE" name="__VIEWSTATE" type="hidden" value="aFYEghTyUFL4Qydyuiugv5hSQ48bdbaHwvBsDayLBMOdqJWVopqLmiKQq1b+Bp2UH8n7D9+3opqrxV1Vh8w6buKTRHlreiWfYWHEFQw91xcxp9na9fOLvqj5cSwtcdhtyKQC+ZTLA44u5Ju+nvXhuatWrvssjEsNzKJrOi5BqdN4spW0C2o7C8O1sybsjX0kHbgbfj5k1+BEwqyYCiWgRYbsYB6KyavSwUf53ulOfP+YLb9shhf4d02cLDt1MLWHb5z8MnjmeUyyclCMFvtRo84yDBs3GmkqJCTSaa7W04MhrObbPO7giTkrDAoMHTiu8BP9VEcyPuOPMNLohfkgVic2freSbrlsmGOWYuP/xPMAs5f9kcLsP7+Qm+fEpkEoUQSf93pGqmZxlSQ+47CwEEOwHk8wfPMc3K4Lmw9jmNl44Gl1+6K8hH2AzjE9zvhH9VML29bvAyS0WS7DWaiBz4eXk6HE3OQNq2BbogVcgicH4vTm+GKINPQJY5h2phCvfz6g4iCmKXPKp7mY8+MWSI5mX+tPKe432d4CLhIKTfC4aHoPQv6wQfCqf1Uk+ebvwoPUZx+pP9RweQwfzJuwZOdMLOvWA+mmjXJbp8ii6hS09045SmfclUAihxz53XnbkUjrgjzsBU/TvVq4qNDyR5IeR97MlWcZXqbmp+VHyneMRJy5MHLu0Q2exJqoYH+6ONzjGo5PEkWTKNKKeVpKkCEvzfIZGuxlgvcaXv3rkfg2fNqoMpIrUNsu+HgrE1rAcfXPQmnCSZJUTA7ScNa5dw7IV8RkOb4C0puFevAAWq9rL8YaqOUMabl5oJuhJ1iXyNhuJs6UGSNWKer3zZhOwVW/f2Q2XBMrFlDndRz0YG3DRZ5uEGcdGFzPSZ+wWK2xs2o5rUKbbQlKStLLdzJnpfsJ2GzWMLQRd7lmTO8d6VcZ4dSzLAZYsTKrC2XvJlC3O4tPbQq0fkpnxnoLa5Lr8xaP4o5ICBrj9OTm4KmVMq0+XjCM8J4Qz9cNFEuzZo6pe506710uhGjR4EbTbXnn/mFhEB4IY9aHHHThHwa7Ic9ihq9yel+fA22Z3PyE4zeRWE+sCarb6IfVRmf1umT2cjKCGX40xvDMNToojTuJRmnsOxRTqFpsqilzIQJ/f1YBhOu8tnJJMGjKzVDdbweJj4kEo0mdhvN/ut+YCy5nW18csb8AIleiz8hKjY7b62k2fBtzADmmjiSFoLneG49PFjsZxV1/qjEtuFLolUq4OLcCYj3PQCmx5Fb/Xk7MdHBo4fVfdUwOOwhlnSrJNmkEgB082+tLozqAbwINQFf5UV4dtm7R0GEzw9EN84jXH2izuxiL12LMMkn3OQrFx1F/HQTaYXqxCO3oD3vA+rE5XGFLX1H8dKqSTgUxL53Q5SLPHuYfgmhk0EszsdVP0MVxQSUw/TyVSfBLSUDgUsEkbudmfhRLMl79TdwWaJPyNJ5mrCIHIY5l86HSaLxXrGOH3DAa0+qrFVyVkQHWecCbcgrf5H0oB2jUEholSX8Gm1gs6d5KPdMTgT+UUpceISvQKBhyzFMaxowO/XrTVoaQB5rAgo+VHzVMChgsVrE+8nVTxcPhsqeNQVF7ToAfGCnmo/opv3jqRAIlWdYG7k9AFBET1Q+L"/>
        <script src="/ScriptResource.axd?d=uHIkleVeDJf4xS50Krz-yASwo0jxcH1q4qOGYFxwEKEoSJvIFXBS51hY2rgsLuNnxiM4PAEy_-tnrAHG2pjqyYvUcUl3dv0-09t1zEV2zBLznsupG4FNzTYEyC7-x8rjU2fYe9CeMXqBwsCjEFDNk-1kTVY1&amp;t=ffffffffbec1863d" type="text/javascript">
        </script>
        <input id="__VIEWSTATEGENERATOR" name="__VIEWSTATEGENERATOR" type="hidden" value="745741BD"/>
        <input id="__EVENTVALIDATION" name="__EVENTVALIDATION" type="hidden" value="XCb9Q+JEvQA2zVZnbBEWeWilJ4fivJKR161EHQLrCRB07bpeWrgO7QvAE9GJTzMS3m49VMqkQ8PBWU2UE+nswjX1glfdMs4toY8DJH3Bh7F5XNfOKFH9TGCZrh2wI++y+lNrlzkhwJm4Ya2pA6M9AVOAc5A="/>
        <input name="__RequestVerificationToken" type="hidden" value="YCRNT91QWNps82c3sDxtkav9QsEW2eA3QRFRFJjpPDf3krsXrQvrHDR7isddfp6uDSrYOfw0JhjdWhSAy-fit5i7E9o1"/>
        <div class="breadcrumbs">
         <ul>
          <li>
           <a href="https://motenmedborgarportal.malmo.se/committees" role="link">
            <html>
             <body>
              Nämnder &amp; Styrelser
             </body>
            </html>
           </a>
          </li>
          <li>
           <html>
            <body>
             Kommunfullmäktige
            </body>
           </html>
          </li>
         </ul>
        </div>
        <input id="committeeOverviewMode" name="ctl00$ctl00$mainPlaceHolder$formBody$CommitteeOverview$committeeOverviewMode" type="hidden"/>
        <div class="row">
         <div class="col-8">
          <h1>
           Kommunfullmäktige
          </h1>
         </div>
         <div class="col-4">
          <div class="view-switch" id="committeeTabs" role="tablist">
           <a aria-controls="meetingsListTabContent" aria-label="Listvy" class="list-switch" data-toggle="tab" href="#meetingsListTabContent" id="listViewSwitcher" role="tab">
           </a>
           <a aria-controls="meetingsCalendarTabContent" aria-label="Kalendervy" class="grid-switch" data-toggle="tab" href="#meetingsCalendarTabContent" id="calendarViewSwitcher" role="tab">
           </a>
          </div>
         </div>
        </div>
        <div id="committeeDetails">
        </div>
        <div class="tab-content">
         <div class="tab-pane" id="meetingsListTabContent" role="tabpanel">
          <a href="/committees/kommunfullmaktige/representatives" id="link">
           Förtroendevalda &gt;
          </a>
          <div class="tabs-page" id="committeeOverviewTabs">
           <div class="tabs-menu">
            <button aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" id="PhonesDropDownButton" type="button">
             Kommande
            </button>
            <div aria-labelledby="PhonesDropDownButton" class="dropdown-menu" role="tablist">
             <a aria-controls="committeesUpcomingContent" aria-selected="True" class="dropdown-item active" data-toggle="tab" href="#committeesUpcomingContent" id="committeesUpcomingButton" role="tab">
              Kommande
             </a>
             <a aria-controls="committeesRecentContent" aria-selected="False" class="dropdown-item" data-toggle="tab" href="#committeesRecentContent" id="committeesRecentButton" role="tab">
              Tidigare
             </a>
            </div>
           </div>
          </div>
          <div class="tab-content">
           <div class="tab-pane active" id="committeesUpcomingContent" role="tabpanel">
            <div class="accessible-table calendar-list">
             <div role="table">
              <div class="box-list meetings-list" role="rowgroup">
               <div class="accessible-table-row calendar-header" role="row">
                <span class="accessible-table-cell cell date" role="columnheader" tabindex="0">
                 Datum
                </span>
                <span class="accessible-table-cell cell location" role="columnheader" tabindex="0">
                 Plats
                </span>
               </div>
               <div class="accessible-table-row calendar-header" role="row">
                <span class="accessible-table-cell cell year" role="columnheader" tabindex="0">
                 2026
                </span>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382370">
                  <a aria-label="Möte 2026-10-15 13:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-10-15">
                   <span class="no-wrap">
                    2026-10-15
                   </span>
                   <span class="no-wrap">
                    13:00 -
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382373">
                  <a aria-label="Möte 2026-10-29 13:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-10-29">
                   <span class="no-wrap">
                    2026-10-29
                   </span>
                   <span class="no-wrap">
                    13:00 -
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382376">
                  <a aria-label="Möte 2026-11-25 09:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-11-25">
                   <span class="no-wrap">
                    2026-11-25
                   </span>
                   <span class="no-wrap">
                    09:00 -
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382379">
                  <a aria-label="Möte 2026-12-15 13:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-12-15">
                   <span class="no-wrap">
                    2026-12-15
                   </span>
                   <span class="no-wrap">
                    13:00 -
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
              </div>
             </div>
            </div>
           </div>
           <div class="tab-pane" id="committeesRecentContent" role="tabpanel">
            <div class="accessible-table calendar-list">
             <div role="table">
              <div class="box-list meetings-list" role="rowgroup">
               <div class="accessible-table-row calendar-header" role="row">
                <span class="accessible-table-cell cell date" role="columnheader" tabindex="0">
                 Datum
                </span>
                <span class="accessible-table-cell cell location" role="columnheader" tabindex="0">
                 Plats
                </span>
               </div>
               <div class="accessible-table-row calendar-header" role="row">
                <span class="accessible-table-cell cell year" role="columnheader" tabindex="0">
                 2026
                </span>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382367">
                  <a aria-label="Möte 2026-09-24 13:00 - 17:40" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-09-24">
                   <span class="no-wrap">
                    2026-09-24
                   </span>
                   <span class="no-wrap">
                    13:00 - 17:40
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382364">
                  <a aria-label="Möte 2026-08-27 13:00 - 21:05" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-08-27">
                   <span class="no-wrap">
                    2026-08-27
                   </span>
                   <span class="no-wrap">
                    13:00 - 21:05
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="382361">
                  <a aria-label="Möte 2026-06-17 13:00 - 21:05" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-06-17">
                   <span class="no-wrap">
                    2026-06-17
                   </span>
                   <span class="no-wrap">
                    13:00 - 21:05
                   </span>
                  </a>
                 </span>
                </div>
                <div class="accessible-table-cell cell location list-item-location" role="cell" tabindex="0">
                 <span class="location-text">
                  Sessionssalen, Rådhuset
                 </span>
                </div>
               </div>
               <div class="accessible-table-row meeting-list-item" role="row">
                <div class="cell date list-item-date" role="cell">
                 <span data-content-id="380836">
                  <a aria-label="Möte 2026-05-28 13:00 - 21:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-05-28">
                   <span class="no-wrap">
                    2026-05-28
                   </span>
                   <span class="no-wrap">
                    13:00 - 21:10
                   </span>
                  </a>
                 </span>
                </div>

In [8]:
links = soup.find_all(
    "a",
    class_="accessible-table-cell",
    # href=lambda href: href and href.startswith("/committees/kommunfullmaktige/mote-")
)
print(links)

[<a aria-label="Möte 2026-10-15 13:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-10-15">
<span class="no-wrap">
                            2026-10-15
                        </span>
<span class="no-wrap">
                            13:00 -
                        </span>
</a>, <a aria-label="Möte 2026-10-29 13:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-10-29">
<span class="no-wrap">
                            2026-10-29
                        </span>
<span class="no-wrap">
                            13:00 -
                        </span>
</a>, <a aria-label="Möte 2026-11-25 09:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-11-25">
<span class="no-wrap">
                            2026-11-25
                        </span>
<span class="no-wrap">
                            09:00 -
                        </span>
</a>, <a aria-label="Möte 2026-12-15 13:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-12-15">
<span class="no-wrap">
                            2026-12-15
                        </span>
<span class="no-wrap">
                            13:00 -
                        </span>
</a>, <a aria-label="Möte 2026-09-24 13:00 - 17:40" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-09-24">
<span class="no-wrap">
                            2026-09-24
                        </span>
<span class="no-wrap">
                            13:00 - 17:40
                        </span>
</a>, <a aria-label="Möte 2026-08-27 13:00 - 21:05" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-08-27">
<span class="no-wrap">
                            2026-08-27
                        </span>
<span class="no-wrap">
                            13:00 - 21:05
                        </span>
</a>, <a aria-label="Möte 2026-06-17 13:00 - 21:05" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-06-17">
<span class="no-wrap">
                            2026-06-17
                        </span>
<span class="no-wrap">
                            13:00 - 21:05
                        </span>
</a>, <a aria-label="Möte 2026-05-28 13:00 - 21:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-05-28">
<span class="no-wrap">
                            2026-05-28
                        </span>
<span class="no-wrap">
                            13:00 - 21:10
                        </span>
</a>, <a aria-label="Möte 2026-04-23 13:00 - 20:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-04-23">
<span class="no-wrap">
                            2026-04-23
                        </span>
<span class="no-wrap">
                            13:00 - 20:30
                        </span>
</a>, <a aria-label="Möte 2026-03-26 13:00 - 19:07" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-03-26">
<span class="no-wrap">
                            2026-03-26
                        </span>
<span class="no-wrap">
                            13:00 - 19:07
                        </span>
</a>, <a aria-label="Möte 2026-02-26 13:00 - 19:35" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-02-26">
<span class="no-wrap">
                            2026-02-26
                        </span>
<span class="no-wrap">
                            13:00 - 19:35
                        </span>
</a>, <a aria-label="Möte 2026-01-22 13:00 - 18:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2026-01-22">
<span class="no-wrap">
                            2026-01-22
                        </span>
<span class="no-wrap">
                            13:00 - 18:30
                        </span>
</a>, <a aria-label="Möte 2025-12-16 13:00 - 16:35" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-12-16">
<span class="no-wrap">
                            2025-12-16
                        </span>
<span class="no-wrap">
                            13:00 - 16:35
                        </span>
</a>, <a aria-label="Möte 2025-11-26 09:00 - 19:00" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-11-26">
<span class="no-wrap">
                            2025-11-26
                        </span>
<span class="no-wrap">
                            09:00 - 19:00
                        </span>
</a>, <a aria-label="Möte 2025-10-30 13:00 - 18:55" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-10-30">
<span class="no-wrap">
                            2025-10-30
                        </span>
<span class="no-wrap">
                            13:00 - 18:55
                        </span>
</a>, <a aria-label="Möte 2025-10-02 13:00 - 16:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-10-02">
<span class="no-wrap">
                            2025-10-02
                        </span>
<span class="no-wrap">
                            13:00 - 16:30
                        </span>
</a>, <a aria-label="Möte 2025-09-11 13:00 - 18:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-09-11">
<span class="no-wrap">
                            2025-09-11
                        </span>
<span class="no-wrap">
                            13:00 - 18:30
                        </span>
</a>, <a aria-label="Möte 2025-06-18 13:00 - 19:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-06-18">
<span class="no-wrap">
                            2025-06-18
                        </span>
<span class="no-wrap">
                            13:00 - 19:45
                        </span>
</a>, <a aria-label="Möte 2025-05-22 13:00 - 19:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-05-22">
<span class="no-wrap">
                            2025-05-22
                        </span>
<span class="no-wrap">
                            13:00 - 19:45
                        </span>
</a>, <a aria-label="Möte 2025-04-24 13:00 - 19:00" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-04-24">
<span class="no-wrap">
                            2025-04-24
                        </span>
<span class="no-wrap">
                            13:00 - 19:00
                        </span>
</a>, <a aria-label="Möte 2025-03-27 13:00 - 16:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-03-27">
<span class="no-wrap">
                            2025-03-27
                        </span>
<span class="no-wrap">
                            13:00 - 16:30
                        </span>
</a>, <a aria-label="Möte 2025-02-27 13:00 - 19:50" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-02-27">
<span class="no-wrap">
                            2025-02-27
                        </span>
<span class="no-wrap">
                            13:00 - 19:50
                        </span>
</a>, <a aria-label="Möte 2025-01-30 13:00 - 15:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2025-01-30">
<span class="no-wrap">
                            2025-01-30
                        </span>
<span class="no-wrap">
                            13:00 - 15:45
                        </span>
</a>, <a aria-label="Möte 2024-12-17 13:00 - 18:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-12-17">
<span class="no-wrap">
                            2024-12-17
                        </span>
<span class="no-wrap">
                            13:00 - 18:30
                        </span>
</a>, <a aria-label="Möte 2024-11-20 09:00 - 18:20" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-11-20">
<span class="no-wrap">
                            2024-11-20
                        </span>
<span class="no-wrap">
                            09:00 - 18:20
                        </span>
</a>, <a aria-label="Möte 2024-10-31 13:00 - 18:15" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-10-31">
<span class="no-wrap">
                            2024-10-31
                        </span>
<span class="no-wrap">
                            13:00 - 18:15
                        </span>
</a>, <a aria-label="Möte 2024-09-26 13:00 - 18:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-09-26">
<span class="no-wrap">
                            2024-09-26
                        </span>
<span class="no-wrap">
                            13:00 - 18:30
                        </span>
</a>, <a aria-label="Möte 2024-08-29 13:00 - 19:15" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-08-29">
<span class="no-wrap">
                            2024-08-29
                        </span>
<span class="no-wrap">
                            13:00 - 19:15
                        </span>
</a>, <a aria-label="Möte 2024-06-19 13:00 - 19:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-06-19">
<span class="no-wrap">
                            2024-06-19
                        </span>
<span class="no-wrap">
                            13:00 - 19:10
                        </span>
</a>, <a aria-label="Möte 2024-05-23 13:00 - 20:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-05-23">
<span class="no-wrap">
                            2024-05-23
                        </span>
<span class="no-wrap">
                            13:00 - 20:30
                        </span>
</a>, <a aria-label="Möte 2024-04-25 13:00 - 19:25" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-04-25">
<span class="no-wrap">
                            2024-04-25
                        </span>
<span class="no-wrap">
                            13:00 - 19:25
                        </span>
</a>, <a aria-label="Möte 2024-03-27 13:00 - 16:25" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-03-27">
<span class="no-wrap">
                            2024-03-27
                        </span>
<span class="no-wrap">
                            13:00 - 16:25
                        </span>
</a>, <a aria-label="Möte 2024-02-29 13:00 - 17:00" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-02-29">
<span class="no-wrap">
                            2024-02-29
                        </span>
<span class="no-wrap">
                            13:00 - 17:00
                        </span>
</a>, <a aria-label="Möte 2024-02-01 13:00 - 16:50" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2024-02-01">
<span class="no-wrap">
                            2024-02-01
                        </span>
<span class="no-wrap">
                            13:00 - 16:50
                        </span>
</a>, <a aria-label="Möte 2023-12-21 13:00 - 18:15" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-12-21">
<span class="no-wrap">
                            2023-12-21
                        </span>
<span class="no-wrap">
                            13:00 - 18:15
                        </span>
</a>, <a aria-label="Möte 2023-11-23 13:00 - 19:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-11-23">
<span class="no-wrap">
                            2023-11-23
                        </span>
<span class="no-wrap">
                            13:00 - 19:10
                        </span>
</a>, <a aria-label="Möte 2023-11-01 09:00 - 19:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-11-01">
<span class="no-wrap">
                            2023-11-01
                        </span>
<span class="no-wrap">
                            09:00 - 19:10
                        </span>
</a>, <a aria-label="Möte 2023-09-28 13:00 - 17:55" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-09-28">
<span class="no-wrap">
                            2023-09-28
                        </span>
<span class="no-wrap">
                            13:00 - 17:55
                        </span>
</a>, <a aria-label="Möte 2023-08-31 13:00 - 16:00" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-08-31">
<span class="no-wrap">
                            2023-08-31
                        </span>
<span class="no-wrap">
                            13:00 - 16:00
                        </span>
</a>, <a aria-label="Möte 2023-06-21 13:00 - 18:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-06-21">
<span class="no-wrap">
                            2023-06-21
                        </span>
<span class="no-wrap">
                            13:00 - 18:45
                        </span>
</a>, <a aria-label="Möte 2023-06-01 13:00 - 16:40" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-06-01">
<span class="no-wrap">
                            2023-06-01
                        </span>
<span class="no-wrap">
                            13:00 - 16:40
                        </span>
</a>, <a aria-label="Möte 2023-04-27 13:00 - 19:20" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-04-27">
<span class="no-wrap">
                            2023-04-27
                        </span>
<span class="no-wrap">
                            13:00 - 19:20
                        </span>
</a>, <a aria-label="Möte 2023-03-23 13:00 - 16:50" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-03-23">
<span class="no-wrap">
                            2023-03-23
                        </span>
<span class="no-wrap">
                            13:00 - 16:50
                        </span>
</a>, <a aria-label="Möte 2023-03-02 13:00 - 16:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-03-02">
<span class="no-wrap">
                            2023-03-02
                        </span>
<span class="no-wrap">
                            13:00 - 16:45
                        </span>
</a>, <a aria-label="Möte 2023-02-02 13:00 - 16:55" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2023-02-02">
<span class="no-wrap">
                            2023-02-02
                        </span>
<span class="no-wrap">
                            13:00 - 16:55
                        </span>
</a>, <a aria-label="Möte 2022-12-20 13:00 - 15:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-12-20">
<span class="no-wrap">
                            2022-12-20
                        </span>
<span class="no-wrap">
                            13:00 - 15:45
                        </span>
</a>, <a aria-label="Möte 2022-11-23 09:00 - 19:00" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-11-23">
<span class="no-wrap">
                            2022-11-23
                        </span>
<span class="no-wrap">
                            09:00 - 19:00
                        </span>
</a>, <a aria-label="Möte 2022-11-03 13:00 - 19:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-11-03">
<span class="no-wrap">
                            2022-11-03
                        </span>
<span class="no-wrap">
                            13:00 - 19:10
                        </span>
</a>, <a aria-label="Möte 2022-10-17 13:00 - 13:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-10-17">
<span class="no-wrap">
                            2022-10-17
                        </span>
<span class="no-wrap">
                            13:00 - 13:45
                        </span>
</a>, <a aria-label="Möte 2022-09-29 13:00 - 15:25" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-09-29">
<span class="no-wrap">
                            2022-09-29
                        </span>
<span class="no-wrap">
                            13:00 - 15:25
                        </span>
</a>, <a aria-label="Möte 2022-09-01 13:00 - 18:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-09-01">
<span class="no-wrap">
                            2022-09-01
                        </span>
<span class="no-wrap">
                            13:00 - 18:10
                        </span>
</a>, <a aria-label="Möte 2022-06-22 09:00 - 17:10" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-06-22">
<span class="no-wrap">
                            2022-06-22
                        </span>
<span class="no-wrap">
                            09:00 - 17:10
                        </span>
</a>, <a aria-label="Möte 2022-05-25 09:00 - 18:50" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-05-25">
<span class="no-wrap">
                            2022-05-25
                        </span>
<span class="no-wrap">
                            09:00 - 18:50
                        </span>
</a>, <a aria-label="Möte 2022-04-28 13:00 - 21:00" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-04-28">
<span class="no-wrap">
                            2022-04-28
                        </span>
<span class="no-wrap">
                            13:00 - 21:00
                        </span>
</a>, <a aria-label="Möte 2022-03-31 13:00 - 20:45" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-03-31">
<span class="no-wrap">
                            2022-03-31
                        </span>
<span class="no-wrap">
                            13:00 - 20:45
                        </span>
</a>, <a aria-label="Möte 2022-03-03 13:00 - 19:50" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-03-03">
<span class="no-wrap">
                            2022-03-03
                        </span>
<span class="no-wrap">
                            13:00 - 19:50
                        </span>
</a>, <a aria-label="Möte 2022-02-03 13:00 - 20:30" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2022-02-03">
<span class="no-wrap">
                            2022-02-03
                        </span>
<span class="no-wrap">
                            13:00 - 20:30
                        </span>
</a>, <a aria-label="Möte 2021-12-21 13:00 - 18:40" aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2021-12-21">
<span class="no-wrap">
                            2021-12-21
                        </span>
<span class="no-wrap">
                            13:00 - 18:40
                        </span>
</a>, <a aria-label="Möte 2021-11-17 09:00 - " aria-live="off" class="accessible-table-cell" href="/committees/kommunfullmaktige/mote-2021-11-17">

In [126]:
meetings = {}

for link in links:
    href = link.get("href")
    aria_label = link.get("aria-label")
    
    if href is not None and aria_label is not None:
        meetings[aria_label] = href

meetings_df = pd.DataFrame(list(meetings.items()), columns=["label", "href"])
meetings_df

,label,href
0,Möte 2026-10-15 13:00 -,/committees/kommunfullmaktige/mote-2026-10-15
1,Möte 2026-10-29 13:00 -,/committees/kommunfullmaktige/mote-2026-10-29
2,Möte 2026-11-25 09:00 -,/committees/kommunfullmaktige/mote-2026-11-25
3,Möte 2026-12-15 13:00 -,/committees/kommunfullmaktige/mote-2026-12-15
4,Möte 2026-09-24 13:00 - 17:40,/committees/kommunfullmaktige/mote-2026-09-24
...,...,...
93,Möte 2019-01-31 13:00 - 17:50,/committees/kommunfullmaktige/mote-2019-01-31
94,Möte 2018-12-20 09:00 - 18:20,/committees/kommunfullmaktige/mote-2018-12-20
95,Möte 2018-11-22 13:00 - 17:47,/committees/kommunfullmaktige/mote-2018-11-22
96,Möte 2018-10-25 13:00 - 18:45,/committees/kommunfullmaktige/mote-2018-10-25
97,Möte 2018-10-15 13:00 - 14:50,/committees/kommunfullmaktige/mote-2018-10-15

In [10]:
base_url = "https://motenmedborgarportal.malmo.se/"

href_10 = str(meetings_df.loc[9, "href"]).lstrip("/")
meeting_url = f"{base_url}/{href_10}"

print(meeting_url)

https://motenmedborgarportal.malmo.se//committees/kommunfullmaktige/mote-2026-03-26

In [11]:
response_meeting = requests.get(meeting_url)

soup_meeting = BeautifulSoup(response_meeting.text, "html.parser")
print(soup_meeting.prettify())

<!DOCTYPE html>
<html class="no-js" lang="sv">
 <head>
  <meta charset="utf-8"/>
  <meta content="Sessionssalen, Rådhuset" name="description"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,height=device-height, initial-scale=1" name="viewport"/>
  <title>
   Möte 2026-03-26 | MeetingPlus [sv]
  </title>
  <link href="/fonts/local-fonts.less" rel="stylesheet" type="text/css"/>
  <link href="/bundles/web-app-styles.css?v=Vmgkl8JuQVcBIDNDg3Js4QVVIA3R9OQxrF0AoR_4bVg1" rel="stylesheet"/>
  <script src="/bundles/libraries.js?v=c6pRkBWBvu7iGhyF15_rDTBj4dsXU3IDLUaGb6CCnhE1">
  </script>
  <script>
   cssVars({ onlyLegacy: true });
  </script>
  <script src="/bundles/accessibleCheckboxControl.js?v=BeKO6qIzC1enkD3RwwKHDChAhTm1YJDm0AONmu6kq_I1">
  </script>
  <script>
   document.meetingsPlusUser = "anonymous";
        document.isMobileClient = false;
        document.acceptLanguageHeaderValue = "sv";

        function getAntiForgeryHeader() {
            var tokenKey = "__RequestVerificationToken";
            var antiForgeryToken = "EE8Pu2rqV9ti_cJeA9QIp4k4jze5G8CIkB2VAjvtXZOiy0NF0L3fkYwFr3ciJ1ZKmb5zaO9DyacSYTbrxzYmwceeomk1";
            var headers = {};
            headers[tokenKey] = antiForgeryToken;
            return headers;
        }



        document.addEventListener("DOMContentLoaded", function () {
            var helpLinks = document.querySelectorAll("a.help-link[data-no-url='true']");
            if (helpLinks.length) {
                helpLinks.forEach(function (hl) {
                    hl.addEventListener("click", function (e) {
                        e.preventDefault();
                        alert("Ingen URL har angivits för hjälpfunktionen, vänligen kontakta administratör.");
                    });
                });
            }
        });
  </script>
  <script>
   NS_CSM_td=6471502;NS_CSM_pd=275116665;NS_CSM_u="/clm10";NS_CSM_col="AAAAAAVxfn2TH970iyRllTe4YbtYB+WmyH6JznPu9bF5xRlaB51VZjIPSmifxeegwAU7pEkSWBjcrPmFU0hD+5mbHNXg";
  </script>
  <script type="text/javascript">
   function sendTimingInfoInit(){setTimeout(sendTimingInfo,0)}function sendTimingInfo(){var wp=window.performance;if(wp){var c1,c2,t;c1=wp.timing;if(c1){var cm={};cm.ns=c1.navigationStart;if((t=c1.unloadEventStart)>0)cm.us=t;if((t=c1.unloadEventEnd)>0)cm.ue=t;if((t=c1.redirectStart)>0)cm.rs=t;if((t=c1.redirectEnd)>0)cm.re=t;cm.fs=c1.fetchStart;cm.dls=c1.domainLookupStart;cm.dle=c1.domainLookupEnd;cm.cs=c1.connectStart;cm.ce=c1.connectEnd;if((t=c1.secureConnectionStart)>0)cm.scs=t;cm.rqs=c1.requestStart;cm.rss=c1.responseStart;cm.rse=c1.responseEnd;cm.dl=c1.domLoading;cm.di=c1.domInteractive;cm.dcls=c1.domContentLoadedEventStart;cm.dcle=c1.domContentLoadedEventEnd;cm.dc=c1.domComplete;if((t=c1.loadEventStart)>0)cm.ls=t;if((t=c1.loadEventEnd)>0)cm.le=t;cm.tid=NS_CSM_td;cm.pid=NS_CSM_pd;cm.ac=NS_CSM_col;var xhttp=new XMLHttpRequest();if(xhttp){var JSON=JSON||{};JSON.stringify=JSON.stringify||function(ob){var t=typeof(ob);if(t!="object"||ob===null){if(t=="string")ob='"'+ob+'"';return String(ob);}else{var n,v,json=[],arr=(ob&&ob.constructor==Array);for(n in ob){v=ob[n];t=typeof(v);if(t=="string")v='"'+v+'"';else if(t=="object"&&v!==null)v=JSON.stringify(v);json.push((arr?"":'"'+n+'":')+String(v));}return(arr?"[":"{")+String(json)+(arr?"]":"}");}};xhttp.open("POST",NS_CSM_u,true);xhttp.send(JSON.stringify(cm));}}}}if(window.addEventListener)window.addEventListener("load",sendTimingInfoInit,false);else if(window.attachEvent)window.attachEvent("onload",sendTimingInfoInit);else window.onload=sendTimingInfoInit;
  </script>
 </head>
 <body class="meeting">
  <a href="#main" id="skipNavigation">
   Hoppa över navigering
  </a>
  <div class="site-wrap">
   <header class="header no-print">
    <div class="container-fluid wrapper">
     <div class="row">
      <div class="col-md-4 w-auto">
       <a href="https://motenmedborgarportal.malmo.se:443/" id="mainLogoLink" role="link">
        <img alt="Malmö Stad, Medborgarportal start" class="main-logo"/>
       </a>
      </div>
      <div class="col-md-4 full-text-search-container">
       <div class="search-global" role="search">
        <input aria-labelledby="full-text-search-label" id="full-text-search" placeholder=" " type="search"/>
        <label for="full-text-search" id="full-text-search-label">
         Sök
        </label>
       </div>
      </div>
      <div class="col-md-4 w-auto">
       <div class="user unlogged">
        <a class="log-link" href="https://motenmedborgarportal.malmo.se/AuthorizationServer/Account/login?client_id=IWP123&amp;client_secret=IWP123&amp;redirect_uri=https%3a%2f%2fmotenmedborgarportal.malmo.se%2fcommittees%2fkommunfullmaktige%2fmote-2026-03-26&amp;language=sv" role="link">
         Logga in
         <span class="log-icon">
         </span>
        </a>
       </div>
      </div>
     </div>
    </div>
    <div class="main-nav">
     <nav aria-label="Huvudmeny" class="nav-menu site-nav-menu">
      <button aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" id="DropDownButton" type="button">
       Nämnder &amp; Styrelser
      </button>
      <ul class="dropdown-menu">
       <li class="">
        <a aria-current="" href="/overview" id="PageLink_overview">
         Översikt
        </a>
       </li>
       <li class="active">
        <a aria-current="page" href="/committees" id="PageLink_committees">
         Nämnder &amp; Styrelser
        </a>
       </li>
       <li class="">
        <a aria-current="" href="/representatives" id="PageLink_representatives">
         Förtroendevalda
        </a>
       </li>
       <li class="">
        <a aria-current="" href="/political-parties" id="PageLink_political-parties">
         Politiska partier
        </a>
       </li>
       <li class="">
        <a aria-current="" href="/digital-bulletin-board" id="PageLink_digital-bulletin-board">
         ANSLAGSTAVLA
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </header>
   <main class="main" id="main">
    <div class="container-fluid wrapper">
     <div class="row">
      <div class="col-12">
       <div class="breadcrumbs">
        <ul>
         <li>
          <a href="https://motenmedborgarportal.malmo.se/committees" role="link">
           <html>
            <body>
             Nämnder &amp; Styrelser
            </body>
           </html>
          </a>
         </li>
         <li>
          <a href="https://motenmedborgarportal.malmo.se/committees/kommunfullmaktige" role="link">
           <html>
            <body>
             Kommunfullmäktige
            </body>
           </html>
          </a>
         </li>
         <li>
          <html>
           <body>
            Möte 2026-03-26
           </body>
          </html>
         </li>
        </ul>
       </div>
       <div class="meeting-brief">
        <div class="row">
         <div class="col-12">
          <div class="meeting-short-info">
           <h1>
            Möte 2026-03-26
           </h1>
          </div>
         </div>
        </div>
        <div class="row">
         <div class="col-12">
          <div class="committee-name">
           Kommunfullmäktige
          </div>
         </div>
        </div>
        <div class="row">
         <div class="col-12">
          <dl aria-label="Möte 2026-03-26 Beskrivning" class="meeting-short-info">
           <dt>
           </dt>
           <dd title="Datum">
            <div class="meeting-chooser">
             <button aria-controls="meetingMenu" aria-expanded="false" aria-haspopup="true" class="dropdown-title" data-toggle="dropdown" id="meetingsSelectorDropdown" type="button">
              2026-03-26
             </button>
             <ul aria-labelledby="meetingsSelectorDropdown" class="dropdown-menu" id="meetingMenu" role="menu">
              <li>
               <h4 class="dropdown-header">
                2026
               </h4>
              </li>
              <li aria-hidden="true" class="dropdown-divider" role="separator">
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-12-15" role="menuitem">
                2026-12-15
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-11-25" role="menuitem">
                2026-11-25
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-10-29" role="menuitem">
                2026-10-29
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-10-15" role="menuitem">
                2026-10-15
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-09-24" role="menuitem">
                2026-09-24
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-08-27" role="menuitem">
                2026-08-27
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-06-17" role="menuitem">
                2026-06-17
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-05-28" role="menuitem">
                2026-05-28
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-04-23" role="menuitem">
                2026-04-23
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <span aria-current="true" class="current">
                2026-03-26
               </span>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-02-26" role="menuitem">
                2026-02-26
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2026-01-22" role="menuitem">
                2026-01-22
               </a>
              </li>
              <li>
               <h4 class="dropdown-header">
                2025
               </h4>
              </li>
              <li aria-hidden="true" class="dropdown-divider" role="separator">
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-12-16" role="menuitem">
                2025-12-16
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-11-26" role="menuitem">
                2025-11-26
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-10-30" role="menuitem">
                2025-10-30
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-10-02" role="menuitem">
                2025-10-02
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-09-11" role="menuitem">
                2025-09-11
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-06-18" role="menuitem">
                2025-06-18
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-05-22" role="menuitem">
                2025-05-22
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-04-24" role="menuitem">
                2025-04-24
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-03-27" role="menuitem">
                2025-03-27
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-02-27" role="menuitem">
                2025-02-27
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2025-01-30" role="menuitem">
                2025-01-30
               </a>
              </li>
              <li>
               <h4 class="dropdown-header">
                2024
               </h4>
              </li>
              <li aria-hidden="true" class="dropdown-divider" role="separator">
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-12-17" role="menuitem">
                2024-12-17
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-11-20" role="menuitem">
                2024-11-20
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-10-31" role="menuitem">
                2024-10-31
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-09-26" role="menuitem">
                2024-09-26
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-08-29" role="menuitem">
                2024-08-29
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-06-19" role="menuitem">
                2024-06-19
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-05-23" role="menuitem">
                2024-05-23
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-04-25" role="menuitem">
                2024-04-25
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-03-27" role="menuitem">
                2024-03-27
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-02-29" role="menuitem">
                2024-02-29
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2024-02-01" role="menuitem">
                2024-02-01
               </a>
              </li>
              <li>
               <h4 class="dropdown-header">
                2023
               </h4>
              </li>
              <li aria-hidden="true" class="dropdown-divider" role="separator">
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-12-21" role="menuitem">
                2023-12-21
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-11-23" role="menuitem">
                2023-11-23
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-11-01" role="menuitem">
                2023-11-01
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-09-28" role="menuitem">
                2023-09-28
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-08-31" role="menuitem">
                2023-08-31
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-06-21" role="menuitem">
                2023-06-21
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-06-01" role="menuitem">
                2023-06-01
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-04-27" role="menuitem">
                2023-04-27
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-03-23" role="menuitem">
                2023-03-23
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-03-02" role="menuitem">
                2023-03-02
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2023-02-02" role="menuitem">
                2023-02-02
               </a>
              </li>
              <li>
               <h4 class="dropdown-header">
                2022
               </h4>
              </li>
              <li aria-hidden="true" class="dropdown-divider" role="separator">
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2022-12-20" role="menuitem">
                2022-12-20
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2022-11-23" role="menuitem">
                2022-11-23
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2022-11-03" role="menuitem">
                2022-11-03
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2022-10-17" role="menuitem">
                2022-10-17
               </a>
              </li>
              <li class="dropdown-item" role="none" tabindex="-1">
               <a href="/committees/kommunfullmaktige/mote-2022-09-29" role="menuitem">
                2022-09-29

In [12]:
protocol = soup_meeting.find_all(
    'a',
    id = 'openProtocol'
)

print(protocol[0])

protocol_href = protocol[0].get("href")

print(protocol_href)

<a aria-expanded="false" aria-haspopup="false" class="button button-diff dropdown-toggle" href="https://motenmedborgarportal.malmo.se/committees/kommunfullmaktige/mote-2026-03-26/protocol/protokoll-kf-26-03-26pdf?downloadMode=open" id="openProtocol" role="button">
            Öppna protokoll
            </a>
https://motenmedborgarportal.malmo.se/committees/kommunfullmaktige/mote-2026-03-26/protocol/protokoll-kf-26-03-26pdf?downloadMode=open

In [13]:
import pdfplumber
from io import BytesIO

In [14]:
response = requests.get(protocol_href)
response.raise_for_status()

In [15]:
with pdfplumber.open(BytesIO(response.content)) as pdf:
    page = pdf.pages[0]
    print(page.extract_text()[:10000])

1
Malmö stad
Kommunfullmäktige
Protokoll
Sammanträdestid 2026-03-26 kl 13:00-19:07
Plats Sessionssalen, Rådhuset
Utses att justera Anders Rubin (S)
Michael Hård af Segerstad (SD)
Justeringen 2026-04-08
Protokollet omfattar §§51-73
Underskrifter Sekreterare
Louise Lagerlund
Ordförande
Carina Nilsson (S) §§ Björn Gudmundsson
51-58, 60-73 (S) § 59
Justerande
Anders Rubin (S) Michael Hård af
Segerstad (SD)

In [16]:
all_lines = []
with pdfplumber.open(BytesIO(response.content)) as pdf:
    for page in pdf.pages:
        text = page.extract_text() or ""
        all_lines.extend(text.splitlines())

In [17]:
print(all_lines)

['1', 'Malmö stad', 'Kommunfullmäktige', 'Protokoll', 'Sammanträdestid 2026-03-26 kl 13:00-19:07', 'Plats Sessionssalen, Rådhuset', 'Utses att justera Anders Rubin (S)', 'Michael Hård af Segerstad (SD)', 'Justeringen 2026-04-08', 'Protokollet omfattar §§51-73', 'Underskrifter Sekreterare', 'Louise Lagerlund', 'Ordförande', 'Carina Nilsson (S) §§ Björn Gudmundsson', '51-58, 60-73 (S) § 59', 'Justerande', 'Anders Rubin (S) Michael Hård af', 'Segerstad (SD)', '2', 'Beslutande ledamöter', 'Katrin Stjernfeldt Jammeh (S) §§56-73', 'Farishta Sulaiman (M)', 'Magnus Olsson (SD)', 'Nina Jakku (V)', 'Andréas Schönström (S)', 'John Roslund (-)', 'Frida Trollmyr (S) §§51-60', 'Rickard Åhman Persson (SD)', 'Mohamed Yassin (MP) §§51-62', 'Carin Gustafsson (V) §§56-73', 'Anders Rubin (S)', 'Roko Kursar (L)', 'Nicola Rabi (M) §§56-73', 'Carina Nilsson (S) (Ordförande)', 'Kay Wictorin (C)', 'Lars-Johan Hallgren (SD)', 'Anja Nordberg Sonesson (M) (Andre vice ordförande)', 'Sofia Hedén (S)', 'Tony Rahm (M) §§51-59', 'Anders Pripp (SD)', 'Mubarik Abdirahman (S)', 'Boel Pettersson (V)', 'Stefana Hoti (MP) §§59-73', 'Amani Loubani (S)', 'Helena Nanne (M)', 'Michael Hård af Segerstad (SD)', 'Bengt-Göran Svensson (S) §§51-63', 'Sadiye Altundal (V)', 'Håkan Fäldt (M)', 'Jacqueline Maly (SD)', 'Juan-Tadeo Espitia (S)', 'John Eklöf (M)', 'Anton Sauer (C) §§51-62', 'Anders Skans (V)', 'Shler Bradostin (S)', 'Haqvin Svensson (M)', 'Björn Gudmundsson (S) (Vice ordförande) §§51-60', 'Surra Al Sakban (MP) §§63-73', 'Sanna Axelsson (S) §§51-68', 'Lisa Stolpe (V) §§51-64', 'Malin Ahlström (M) §§56-57', 'Håkan Ask (SD) §§51-67', 'Arwin Sohrabi Nejad (S)', 'Sara Wettergren (L)', 'Christina Wessling (S)', 'Linda Obiedzinski (M)', 'Lisbeth Persson Ekström (SD)', 'Jan Olsson (S)', 'Helena Grahn (M)', 'Susanne Jönsson (S)', 'Anders Andersson (V)', 'Dündar Güngör (S)', '3', 'Anders Olin (SD)', 'Janne Grönholm (MP)', 'Albin Schyllert (M)', 'Hanna Sandberg (S) ersätter Sedat Arif (S)', 'Nadjam-Ud-Din Malik (S) §§51-55 ersätter Katrin Stjernfeldt Jammeh (S), §§69-73 ersätter', 'Sanna Axelsson (S)', 'Anders Nilsson (S) ersätter Olga Krivtsova (S)', 'Marie Tanndal (S) §§61-73 ersätter Björn Gudmundsson (S) (Vice ordförande)', 'Peter Johansson (S) §§61-73 ersätter Frida Trollmyr (S)', 'Shaip Morina (S) §§64-73 ersätter Bengt-Göran Svensson (S)', 'Ingrid Gunnarson (M) §§51-55 ersätter Nicola Rabi (M), §§58-64 ersätter Malin Ahlström', '(M)', 'Mats Brogren (M) §§51-55 ersätter Malin Ahlström (M), §§60-73 ersätter Tony Rahm (M)', 'Darko Simic (M) §§65-73 ersätter Malin Ahlström (M)', 'Jenny Bengtsson (SD) ersätter Jörgen Grubb (SD)', 'Stefan Claesson (SD) §§68-73 ersätter Håkan Ask (SD)', 'Marek Lakatos (V) §§51-69 ersätter Anfal Mahdi (V)', 'Tobias Petersson (V) ersätter Showan Shattak (V)', 'Kerstin Håkansson (V) §§51-55 ersätter Carin Gustafsson (V), §§65-73 ersätter Lisa Stolpe', '(V)', 'Ana Maria Stuparich-Clementi (V) §§70-73 ersätter Anfal Mahdi (V)', 'Anna Ljunggren (MP) §§51-58 ersätter Stefana Hoti (MP), §§63-73 ersätter Mohamed', 'Yassin (MP)', 'Erik Hammarström (MP) §§51-62 ersätter Surra Al Sakban (MP)', 'Eva Bertz (L) §§51-64 ersätter Linda Eklund (L)', 'Joel Laguna Ascacivar (L) §§65-73 ersätter Linda Eklund (L)', 'Martin Molin (C) §§63-73 ersätter Anton Sauer (C)', 'Ej tjänstgörande ersättare', 'Nadjam-Ud-Din Malik (S) §§56-68', 'Marie Tanndal (S) §§51-60', 'Peter Johansson (S) §§51-60', 'Amanda Johannesson (S)', 'Shaip Morina (S) §§51-63', 'Birgit Hansson (S)', 'Sven-Erik Rasmusson (S)', 'Neziya Rahman (S)', 'Ingrid Gunnarson (M) §§56-57, §§65-73', 'Mats Brogren (M) §§56-59', 'Darko Simic (M) §§51-64', 'Petra Lundgren (-)', 'Danica Srnic (M)', 'Stefan Claesson (SD) §§51-67', 'Nichlas Holmgren Gellersten (SD)', 'Eva Hallén (SD)', 'Patrick Angelin (SD) §§51-67', 'Marek Lakatos (V) §§70-73', 'Kerstin Håkansson (V) §§56-64', 'Ana Maria Stuparich-Clementi (V) §§51-69', 'Anna Ljunggren (MP) §§59-62', 'Erik Hammarström (MP) §§63-73', 'Eva Bertz (L) §§65-73', 'Joel Laguna Ascacivar (L) §§51-64', '4', 'Martin Molin (C) §§51-62', 'Ewa Langerbeck (C)', 'Övriga närvarande', 'Louise Lagerlund (stadsjurist)', 'Nicklas Löfström (nämndsekreterare)', 'Pamela Lindqvist (nämndsekreterare)', 'Isabelle Henningsson (nämndsekreterare)', '5', 'ÄRENDELISTA', '§51 Upprop och ordförandens upplysning angående webbsändning av', 'kommunfullmäktigesammanträdet', '§52 Val av justerare', '§53 Beslut från Länsstyrelsen Skåne om nya ledamöter och ersättare i', 'kommunfullmäktige 2026', '§54 Inkomna frågor', '§55 Besvarande av frågor', '§56 Ansökan om utökad låneram Malmö Leasing AB', '§57 Uppdrag budget 2024 - modell för att underlätta övergången från daglig', 'verksamhet till en kommunal arbetsmarknadsanställning, eller till den', 'reguljära arbetsmarknaden för Malmöbor med funktionsnedsätt', '§58 Utökade objektsgodkännanden MEX4', '§59 Hemställan från SYSAV om förstärkt finansiering av investering i en', 'koldioxidinfångningsanläggning (SkyZero), samt köp av negativa', 'utsläppscertifikat', '§60 Detaljplan för del av fastigheten Innerstaden 9:173 m.fl. i Stadion (Dp', '5892)', '§61 Revidering av Plan för arbetet mot islamofobi och antimuslimsk rasism', '§62 Plan för arbetet mot afrofobi och antisvart rasism', '§63 Motion Anfal Mahdi (V) om att uppmärksamma Palestinska jordens dag', '§64 Motion Tobias Petersson (V) och Lisa Stolpe (V) om att det ska vara lätt', 'att ta sig till rekreation', '§65 Motion Lisbeth Persson Ekström (SD) om äldredräkt', '§66 Motion Anders Olin (SD) om flytt av ansvar för markanvisningsavtal från', 'Tekniska nämnden till Stadsbyggnadsnämnden', '§67 Motion Jenny Bengtsson (SD), Anders Pripp (SD), Håkan Ask (SD) om', 'åtgärder för att hantera råttproblematiken i Malmö', '§68 Motion Nicola Rabi (M) - För ett tryggt tillgängligt och hållbart nattliv i', 'Malmö', '§69 Valförslag och avsägelser - Kommunfullmäktige 2026-03-26', '§70 Anmälan av inkomna skrivelser', '§71 Anmälan av inkomna ärenden som ännu inte underställts', 'kommunfullmäktiges prövning', '§72 Inkomna interpellationer', '§73 Besvarande av interpellationer', '6', '§ 51 Upprop och ordförandens upplysning angående webbsändning av', 'kommunfullmäktigesammanträdet', 'Sammanfattning', 'Ordföranden uttalar att "det särskilt ska upplysas om att vid kommunfullmäktiges', 'sammanträde, liksom vid den vidare hanteringen av varje enskilt sammanträde, tillämpas', 'gällande integritetslagstiftning vid all behandling av personuppgifter. De som deltar i', 'kommunfullmäktiges sammanträde erinras om att de inte får röja enskildas sekretess".', 'Upprop förrättas.', '7', '§ 52 Val av justerare', 'Sammanfattning', 'Ordföranden meddelar att protokollet justeras den 8 april 2026 kl 13.00 på stadskontoret.', 'Kommunfullmäktige utser Michael Hård af Segerstad (SD) och Anders Rubin (S) att jämte', 'ordföranden justera protokollet.', '8', '§ 53 Beslut från Länsstyrelsen Skåne om nya ledamöter och ersättare i', 'kommunfullmäktige 2026', 'STK-2026-20', 'Sammanfattning', 'Enligt från Länsstyrelsen i Skåne län inkommit protokoll har Lisa Stolpe (V) utsetts till ny', 'ledamot och Ana Maria Stuparich-Clementi (V) till ny ersättare efter Gunilla Ryd (V) som', 'avgått som ledamot.', 'Enligt från Länsstyrelsen i Skåne län inkommit protokoll har Danica Srnic (M) utsetts till', 'ny ersättare efter Niclas Röhr (M) som avgått som ersättare.', 'Beslut', 'Kommunfullmäktige beslutar', '1. Kommunfullmäktige lägger länsstyrelsens protokoll till handlingarna.', '9', '§ 54 Inkomna frågor', 'STK-2026-422', 'Sammanfattning', 'Jacqueline Maly (SD) har anhållit om att till arbetsmarknads- och socialnämndens', 'ordförande Sedat Arif (S) få framställa en fråga om etablering av fler familjecentraler för', 'jämlika uppväxtvillkor över hela staden.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde av grundskolenämndens ordförande Sara Wettergren (L).', 'Lisbeth Persson-Ekström (SD) har anhållit om att till hälsa-, vård- och omsorgsnämndens', 'ordförande Anders Rubin (S) få framställa en fråga om missförhållande på äldreboende i', 'Västra Hamnen.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Lisa Stolpe (V) har anhållit om att till förskolenämndens ordförande Mohamed Yassin', '(MP) få framställa en fråga om barngruppernas storlek för ökad säkerhet.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Lisbeth Persson-Ekström (SD) har anhållit om att till hälsa-, vård- och omsorgsnämndens', 'ordförande Anders Rubin (S) få framställa en fråga om våldtäkt inom hemtjänsten.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Nina Jakku (V) har anhållit om att till grundskolenämndens ordförande Sara Wettergren (L)', 'få framställa en fråga om resursskolan.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Marek Lakatos (V) har anhållit om att till fritidsnämndens ordförande Sanna Axelsson (S)', 'få framställa en fråga om aktiviteter för barn inom Kul i Malmö.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Albin Schyllert (M) har anhållit om att till hälsa-, vård- och omsorgsnämndens ordförande', 'Anders Rubin (S) få framställa en fråga om äldres trygghet vid integritetskänsliga', 'omsorgsinsatser.', '10', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Kay Wictorin (C) har anhållit om att till hälsa-, vård- och omsorgsnämndens ordförande', 'Anders Rubin (S) få framställa en fråga angående polisanmälan och hantering av misstänkt', 'brott av anställd i Malmö stads verksamhet.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde.', 'Helena Nanne (M) har anhållit om att till kommunstyrelsens ordförande Katrin Stjernfeldt', 'Jammeh (S) få framställa en fråga om välfärdens konsekvenser av arbetstidsförkortning.', 'Kommunfullmäktige medger att frågan får framställas. Den kommer att besvaras vid', 'dagens sammanträde av hälsa-, vård- och omsorgsnämndens ordförande Anders Rubin (S).', 'Beslutsunderlag', '• Fråga från Jacqueline Maly (SD) till Sedat Arif (S) om etablering av fler', 'familjecentraler för jämlika uppväxtvillkor över hela staden', '• Fråga från Lisbeth Persson-Ekström (SD) till Anders Rubin (S) om missförhållande', 'på äldreboende i Västra Hamnen', '• Fråga från Lisa Stolpe (V) till Mohamed Yassin (MP) om barngruppernas storlek', 'för ökad säkerhetansvarigt kommunalråd', '• Fråga från Lisbeth Persson-Ekström (SD) till Anders Rubin (S) om våldtäkt inom', 'hemtjänsten', '• Fråga från Nina Jakku (V) till Sara Wettergren (L) om resursskolan', '• Fråga från Marek Lakatos (V) till Sanna Axelsson (S) om aktiviteter för barn inom', 'Kul i Malmö', '• Fråga från Albin Schyllert (M) till Anders Rubin (S) om äldres trygghet vid', 'integritetskänsliga omsorgsinsatser', '• Fråga från Kay Wictorin (C) till Anders Rubin (S) angående polisanmälan och', 'hantering av misstänkt brott av anställd i Malmö stads verksamhet', '• Fråga från Helena Nanne (M) till Katrin Stjernfeldt Jammeh (S) om välfärdens', 'konsekvenser av arbetstidförkortning', '11', '§ 55 Besvarande av frågor', 'STK-2026-423', 'Sammanfattning', 'Kommunfullmäktige beslutade under § 54 medge Albin Schyllert (M) att till hälsa-, vård-', 'och omsorgsnämndens ordförande Anders Rubin (S) få framställa en fråga om äldres', 'trygghet vid integritetskänsliga omsorgsinsatser.', 'Anders Rubin (S) besvarar frågan. Albin Schyllert (M) yttrar sig.', 'Frågan intas som bilaga 1 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Lisbeth Persson-Ekström (SD) att till', 'hälsa-, vård- och omsorgsnämndens ordförande Anders Rubin (S) få framställa en fråga om', 'om våldtäkt inom hemtjänsten.', 'Anders Rubin (S) besvarar frågan. Lisbeth Persson-Ekström (SD) yttrar sig.', 'Frågan intas som bilaga 2 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Nina Jakku (V) att till', 'grundskolenämndens ordförande Sara Wettergren (L) få framställa en fråga om', 'resursskolan.', 'Sara Wettergren (L) besvarar frågan. Nina Jakku (V) yttrar sig.', 'Frågan intas som bilaga 3 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Kay Wictorin (C) att till hälsa-, vård- och', 'omsorgsnämndens ordförande Anders Rubin (S) få framställa en fråga angående', 'polisanmälan och hantering av misstänkt brott av anställd i Malmö stads verksamhet.', 'Anders Rubin (S) besvarar frågan. Kay Wictorin (C) yttrar sig.', 'Frågan intas som bilaga 4 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Jacqueline Maly (SD) att till', 'grundskolenämndens ordförande Sara Wettergren (L) få framställa en fråga om etablering', 'av fler familjecentraler för jämlika uppväxtvillkor över hela staden.', 'Sara Wettergren (L) besvarar frågan. Jacqueline Maly (SD) yttrar sig.', 'Frågan intas som bilaga 5 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Lisbeth Persson-Ekström (SD) att till', 'hälsa-, vård- och omsorgsnämndens ordförande Anders Rubin (S) få framställa en fråga om', '12', 'missförhållande på äldreboende i Västra Hamnen.', 'Anders Rubin (S) besvarar frågan. Lisbeth Persson-Ekström (SD) yttrar sig.', 'Frågan intas som bilaga 6 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Lisa Stolpe (V) att till förskolenämndens', 'ordförande Mohamed Yassin (MP) få framställa en fråga om barngruppernas storlek för', 'ökad säkerhet.', 'Mohammed Yassin (MP) besvarar frågan. Lisa Stolpe (V) yttrar sig.', 'Frågan intas som bilaga 7 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Marek Lakatos (V) att till', 'fritidsnämndens ordförande Sanna Axelsson (S) få framställa en fråga om aktiviteter för', 'barn inom Kul i Malmö.', 'Sanna Axelsson (S) besvarar frågan. Marek Lakatos (V) yttrar sig.', 'Frågan intas som bilaga 8 § 55.', 'Kommunfullmäktige beslutade under § 54 medge Helena Nanne (M) att till hälsa-, vård-', 'och omsorgsnämndens ordförande Anders Rubin (S) få framställa en fråga om välfärdens', 'konsekvenser av arbetstidsförkortning.', 'Anders Rubin (S) besvarar frågan. Helena Nanne (M) yttrar sig.', 'Frågan intas som bilaga 9 § 55.', 'Beslutsunderlag', '• Fråga från Albin Schyllert (M) till Anders Rubin (S) om äldres trygghet vid', 'integritetskänsliga omsorgsinsatser', '• Fråga från Lisbeth Persson-Ekström (SD) till Anders Rubin (S) om våldtäkt inom', 'hemtjänsten', '• Fråga från Nina Jakku (V) till Sara Wettergren (L) om resursskolan', '• Fråga från Kay Wictorin (C) till Anders Rubin (S) angående polisanmälan och', 'hantering av misstänkt brott av anställd i Malmö stads verksamhet', '• Fråga från Jacqueline Maly (SD) till Sedat Arif (S) om etablering av fler', 'familjecentraler för jämlika uppväxtvillkor över hela staden', '• Fråga från Lisbeth Persson-Ekström (SD) till Anders Rubin (S) om missförhållande', 'på äldreboende i Västra Hamnen', '• Fråga från Lisa Stolpe (V) till Mohamed Yassin (MP) om barngruppernas storlek', 'för ökad säkerhetansvarigt kommunalråd', '13', '• Fråga från Marek Lakatos (V) till Sanna Axelsson (S) om aktiviteter för barn inom', 'Kul i Malmö', '• Fråga från Helena Nanne (M) till Katrin Stjernfeldt Jammeh (S) om välfärdens', 'konsekvenser av arbetstidförkortning', '14', '§ 56 Ansökan om utökad låneram Malmö Leasing AB', 'STK-2025-1926', 'Sammanfattning', 'Styrelsen för Malmö Leasing AB har inkommit med ansökan om utökad låneram för', 'bolaget med 700 mnkr. Malmö Leasing AB har för avsikt att fr.o.m. 2026 byta ut 250', 'fordon per år mot eldrivna fordon fram t.o.m. 2029, d.v.s. totalt 1 000 fordon.', 'Elektrifieringen av fordonsflottan följer Malmö stads målsättningar avseende', 'klimatsomställningen, varav ”Fordonsstrategin för Malmö stad”, som antogs av', 'kommunfullmäktige i december 2023, är en del. I fordonsstrategin framgår bland annat att', 'Malmö stads fordonsflotta ska elektrifieras till 2030, vilket ställer krav på Malmö Leasing', 'AB avseende investeringar i nya fordon.', 'Malmö Leasing AB har därför hos Internbanken ansökt om utökad låneram, vilket', 'Internbanken nu föreslår kommunfullmäktige ta ställning till. Låneramen föreslås utökas', 'från 250 mnkr till 950 mnkr.', 'Beslut', 'Kommunfullmäktige beslutar', '1. Kommunfullmäktige utökar Malmö Leasing AB:s låneram från 250 mnkr till 950', 'mnkr.', 'Beslutsgång', 'Katrin Stjernfeldt Jammeh (S) yrkar bifall till kommunstyrelsens förslag till beslut.', 'Magnus Olsson (SD) yrkar avslag på kommunstyrelsens förslag till beslut.', 'Kommunfullmäktige godkänner följande propositionsordning.', 'Ordföranden ställer proposition på bifall till kommunstyrelsens förslag till beslut mot', 'avslag och finner att kommunfullmäktige beslutat att bifalla kommunstyrelsens förslag till', 'beslut.', 'Reservationer och särskilda yttranden', 'Mot kommunfullmäktiges beslut anmäler Magnus Olsson (SD) gruppreservation som', 'samtliga ledamöter i Sverigedemokraterna ställer sig bakom.', '15', 'Beslutet skickas till', 'Malmö Leasing AB', 'Bolagsavdelningen, stadskontoret', 'Stadskontorets handläggare', 'Beslutsunderlag', '• Förslag till beslut KS 260304 §110 med skriftlig reservation (SD) Ansökan om', 'utökad låneram Malmö Leasing AB', '• Förslag till beslut KSAU 260216 §92 Ansökan om utökad låneram Malmö Leasing', 'AB', '• G-Tjänsteskrivelse KSAU 260216 Ansökan om utökad låneram Malmö Leasing AB', '• G-Tjänsteskrivelse KSAU 2026-02-09 Ansökan om utökad låneram Malmö Leasing', 'AB', '• Följebrev - Ansökan om utökad låneram Malmö Leasing AB', '• Utökad låneram Malmö Leasing AB', '• Likviditetsprognos 2026', '• RR 2026-2029 Malmö Leasing AB', '• Budget 2026', '• Upplåningsbehov 2026-2031', '• Protokoll 5 Malmö Leasing AB - Styrelsen - 2025-12-05 ej sign', '• Tjänsteskrivelse ansökan utökad låneram', '• Ramar för upplåning, borgen och utlåning 2026-03-26 Tillgänglighetsanpassad', '16', '§ 57 Uppdrag budget 2024 - modell för att underlätta övergången från', 'daglig verksamhet till en kommunal arbetsmarknadsanställning,', 'eller till den reguljära arbetsmarknaden för Malmöbor med', 'funktionsnedsätt', 'STK-2025-1854', 'Sammanfattning', 'I budget 2024 fick funktionsstödsnämnden och arbetsmarknads- och socialnämnden i', 'uppdrag att ta fram en modell som underlättar övergångar från daglig verksamhet till en', 'kommunal arbetsmarknadsanställning eller till den reguljära arbetsmarknaden.', 'Funktionsstödsnämnden och arbetsmarknads- och socialnämnden har godkänt', 'återrapportering och ställer sig positiva till den framtagna modellen. I ärendet finns även', 'yttrande från funktionshinderrådet. Föreligger fråga om kommunfullmäktiges godkännande', 'av återrapportering av budgetuppdraget.', 'Beslut', 'Kommunfullmäktige beslutar', '1. Kommunfullmäktige godkänner återrapporteringen från funktionsstödsnämnden', 'och arbetsmarknads- och socialnämnden av uppdrag budget 2024 om modell för', 'att underlätta övergången från daglig verksamhet till en kommunal', 'arbetsmarknadsanställning, eller till den reguljära arbetsmarknaden för Malmöbor', 'med funktionsnedsättning.', 'Beslutsgång', 'Roko Kursar (L) yrkar bifall till kommunstyrelsens förslag till beslut.', 'Under överläggningen i ärendet yttrar sig även Malin Ahlström (M) och Kay Wictorin (C).', 'Ordföranden konstaterar att kommunfullmäktige beslutat att bifalla kommunstyrelsens', 'förslag till beslut.', 'Reservationer och särskilda yttranden', 'Till kommunfullmäktiges beslut i ärendet har Håkan Fäldt (M) och Anton Sauer (C)', 'inkommit med ett gemensamt särskilt yttrande som samtliga ledamöter inom Moderaterna', 'och Centerpartiet ställer sig bakom.', 'Det särskilda yttrandet intas som bilaga 1 § 57 till kommunfullmäktiges protokoll.', 'Beslutet skickas till', 'Funktionsstödsnämnden', 'Arbetsmarknads- och socialnämnden', 'Malmö stads funktionshinderråd', '17', 'Stadskontoret, Omvärld och näringslivsavdelnin

In [18]:
voting_members = []

voting_member_section = False

for line in all_lines:
    lower = line.lower()

    if lower.strip().isdigit():
        continue

    if "beslutande ledamöter" in lower:
        voting_member_section = True
        continue

    if "ersätter" in lower:
        break

    if voting_member_section:
        voting_members.append(line)

In [19]:
print(voting_members)

['Katrin Stjernfeldt Jammeh (S) §§56-73', 'Farishta Sulaiman (M)', 'Magnus Olsson (SD)', 'Nina Jakku (V)', 'Andréas Schönström (S)', 'John Roslund (-)', 'Frida Trollmyr (S) §§51-60', 'Rickard Åhman Persson (SD)', 'Mohamed Yassin (MP) §§51-62', 'Carin Gustafsson (V) §§56-73', 'Anders Rubin (S)', 'Roko Kursar (L)', 'Nicola Rabi (M) §§56-73', 'Carina Nilsson (S) (Ordförande)', 'Kay Wictorin (C)', 'Lars-Johan Hallgren (SD)', 'Anja Nordberg Sonesson (M) (Andre vice ordförande)', 'Sofia Hedén (S)', 'Tony Rahm (M) §§51-59', 'Anders Pripp (SD)', 'Mubarik Abdirahman (S)', 'Boel Pettersson (V)', 'Stefana Hoti (MP) §§59-73', 'Amani Loubani (S)', 'Helena Nanne (M)', 'Michael Hård af Segerstad (SD)', 'Bengt-Göran Svensson (S) §§51-63', 'Sadiye Altundal (V)', 'Håkan Fäldt (M)', 'Jacqueline Maly (SD)', 'Juan-Tadeo Espitia (S)', 'John Eklöf (M)', 'Anton Sauer (C) §§51-62', 'Anders Skans (V)', 'Shler Bradostin (S)', 'Haqvin Svensson (M)', 'Björn Gudmundsson (S) (Vice ordförande) §§51-60', 'Surra Al Sakban (MP) §§63-73', 'Sanna Axelsson (S) §§51-68', 'Lisa Stolpe (V) §§51-64', 'Malin Ahlström (M) §§56-57', 'Håkan Ask (SD) §§51-67', 'Arwin Sohrabi Nejad (S)', 'Sara Wettergren (L)', 'Christina Wessling (S)', 'Linda Obiedzinski (M)', 'Lisbeth Persson Ekström (SD)', 'Jan Olsson (S)', 'Helena Grahn (M)', 'Susanne Jönsson (S)', 'Anders Andersson (V)', 'Dündar Güngör (S)', 'Anders Olin (SD)', 'Janne Grönholm (MP)', 'Albin Schyllert (M)']

In [51]:
def split_first_member(member: str) -> tuple[dict[str, str | None], str]:

    name, rest = member.strip().split("(", 1)
    name = name.strip()

    party, rest = rest.strip().split(")",1)
    party = party.strip()

    rest = rest.strip()

    if rest.startswith('('):
        title, rest = rest.split(')',1)
        title = title.replace('(', '')
    else:
        title = None

    structured_member = {
        'name': name,
        'party': party,
        'title': title
    }

    return structured_member, rest.strip()

In [56]:
def paragraph_interval(paragraph: str) -> list[int] | None:
    if '§' not in paragraph:
        return None

    paragraph = paragraph.replace('§', '').strip()
    paragraphs = paragraph.split(',')

    expanded = []

    for part in paragraphs:
        part = part.strip()

        if '-' in part:
            start, end = map(int, part.split('-'))
            expanded.extend(range(start, end + 1))
        else:
            expanded.append(int(part))

    return expanded

In [62]:
voting_members_dict = []

for member in voting_members:

    structured_member, rest = split_first_member(member)
    paragraph = paragraph_interval(rest)

    voting_members_dict.append(
        {
            'name': structured_member['name'],
            'party': structured_member['party'],
            'paragraphs': paragraph
        }
    )


print(voting_members_dict)

[{'name': 'Katrin Stjernfeldt Jammeh', 'party': 'S', 'paragraphs': [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}, {'name': 'Farishta Sulaiman', 'party': 'M', 'paragraphs': None}, {'name': 'Magnus Olsson', 'party': 'SD', 'paragraphs': None}, {'name': 'Nina Jakku', 'party': 'V', 'paragraphs': None}, {'name': 'Andréas Schönström', 'party': 'S', 'paragraphs': None}, {'name': 'John Roslund', 'party': '-', 'paragraphs': None}, {'name': 'Frida Trollmyr', 'party': 'S', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]}, {'name': 'Rickard Åhman Persson', 'party': 'SD', 'paragraphs': None}, {'name': 'Mohamed Yassin', 'party': 'MP', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]}, {'name': 'Carin Gustafsson', 'party': 'V', 'paragraphs': [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}, {'name': 'Anders Rubin', 'party': 'S', 'paragraphs': None}, {'name': 'Roko Kursar', 'party': 'L', 'paragraphs': None}, {'name': 'Nicola Rabi', 'party': 'M', 'paragraphs': [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}, {'name': 'Carina Nilsson', 'party': 'S', 'paragraphs': None}, {'name': 'Kay Wictorin', 'party': 'C', 'paragraphs': None}, {'name': 'Lars-Johan Hallgren', 'party': 'SD', 'paragraphs': None}, {'name': 'Anja Nordberg Sonesson', 'party': 'M', 'paragraphs': None}, {'name': 'Sofia Hedén', 'party': 'S', 'paragraphs': None}, {'name': 'Tony Rahm', 'party': 'M', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59]}, {'name': 'Anders Pripp', 'party': 'SD', 'paragraphs': None}, {'name': 'Mubarik Abdirahman', 'party': 'S', 'paragraphs': None}, {'name': 'Boel Pettersson', 'party': 'V', 'paragraphs': None}, {'name': 'Stefana Hoti', 'party': 'MP', 'paragraphs': [59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}, {'name': 'Amani Loubani', 'party': 'S', 'paragraphs': None}, {'name': 'Helena Nanne', 'party': 'M', 'paragraphs': None}, {'name': 'Michael Hård af Segerstad', 'party': 'SD', 'paragraphs': None}, {'name': 'Bengt-Göran Svensson', 'party': 'S', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]}, {'name': 'Sadiye Altundal', 'party': 'V', 'paragraphs': None}, {'name': 'Håkan Fäldt', 'party': 'M', 'paragraphs': None}, {'name': 'Jacqueline Maly', 'party': 'SD', 'paragraphs': None}, {'name': 'Juan-Tadeo Espitia', 'party': 'S', 'paragraphs': None}, {'name': 'John Eklöf', 'party': 'M', 'paragraphs': None}, {'name': 'Anton Sauer', 'party': 'C', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]}, {'name': 'Anders Skans', 'party': 'V', 'paragraphs': None}, {'name': 'Shler Bradostin', 'party': 'S', 'paragraphs': None}, {'name': 'Haqvin Svensson', 'party': 'M', 'paragraphs': None}, {'name': 'Björn Gudmundsson', 'party': 'S', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]}, {'name': 'Surra Al Sakban', 'party': 'MP', 'paragraphs': [63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}, {'name': 'Sanna Axelsson', 'party': 'S', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]}, {'name': 'Lisa Stolpe', 'party': 'V', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]}, {'name': 'Malin Ahlström', 'party': 'M', 'paragraphs': [56, 57]}, {'name': 'Håkan Ask', 'party': 'SD', 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]}, {'name': 'Arwin Sohrabi Nejad', 'party': 'S', 'paragraphs': None}, {'name': 'Sara Wettergren', 'party': 'L', 'paragraphs': None}, {'name': 'Christina Wessling', 'party': 'S', 'paragraphs': None}, {'name': 'Linda Obiedzinski', 'party': 'M', 'paragraphs': None}, {'name': 'Lisbeth Persson Ekström', 'party': 'SD', 'paragraphs': None}, {'name': 'Jan Olsson', 'party': 'S', 'paragraphs': None}, {'name': 'Helena Grahn', 'party': 'M', 'paragraphs': None}, {'name': 'Susanne Jönsson', 'party': 'S', 'paragraphs': None}, {'name': 'Anders Andersson', 'party': 'V', 'paragraphs': None}, {'name': 'Dündar Güngör', 'party': 'S', 'paragraphs': None}, {'name': 'Anders Olin', 'party': 'SD', 'paragraphs': None}, {'name': 'Janne Grönholm', 'party': 'MP', 'paragraphs': None}, {'name': 'Albin Schyllert', 'party': 'M', 'paragraphs': None}]

In [23]:
voting_extras = []

voting_member_section = False

for line in all_lines:
    lower = line.lower()

    if voting_members[-1].lower() in lower:
        voting_member_section = True
        continue

    if "ej tjänstgörande ersättare" in lower:
        break

    if voting_member_section:
        voting_extras.append(line)

In [24]:
print(voting_extras)

['Hanna Sandberg (S) ersätter Sedat Arif (S)', 'Nadjam-Ud-Din Malik (S) §§51-55 ersätter Katrin Stjernfeldt Jammeh (S), §§69-73 ersätter', 'Sanna Axelsson (S)', 'Anders Nilsson (S) ersätter Olga Krivtsova (S)', 'Marie Tanndal (S) §§61-73 ersätter Björn Gudmundsson (S) (Vice ordförande)', 'Peter Johansson (S) §§61-73 ersätter Frida Trollmyr (S)', 'Shaip Morina (S) §§64-73 ersätter Bengt-Göran Svensson (S)', 'Ingrid Gunnarson (M) §§51-55 ersätter Nicola Rabi (M), §§58-64 ersätter Malin Ahlström', '(M)', 'Mats Brogren (M) §§51-55 ersätter Malin Ahlström (M), §§60-73 ersätter Tony Rahm (M)', 'Darko Simic (M) §§65-73 ersätter Malin Ahlström (M)', 'Jenny Bengtsson (SD) ersätter Jörgen Grubb (SD)', 'Stefan Claesson (SD) §§68-73 ersätter Håkan Ask (SD)', 'Marek Lakatos (V) §§51-69 ersätter Anfal Mahdi (V)', 'Tobias Petersson (V) ersätter Showan Shattak (V)', 'Kerstin Håkansson (V) §§51-55 ersätter Carin Gustafsson (V), §§65-73 ersätter Lisa Stolpe', '(V)', 'Ana Maria Stuparich-Clementi (V) §§70-73 ersätter Anfal Mahdi (V)', 'Anna Ljunggren (MP) §§51-58 ersätter Stefana Hoti (MP), §§63-73 ersätter Mohamed', 'Yassin (MP)', 'Erik Hammarström (MP) §§51-62 ersätter Surra Al Sakban (MP)', 'Eva Bertz (L) §§51-64 ersätter Linda Eklund (L)', 'Joel Laguna Ascacivar (L) §§65-73 ersätter Linda Eklund (L)', 'Martin Molin (C) §§63-73 ersätter Anton Sauer (C)']

In [25]:
import re

In [63]:
voting_extras_merged = []

extra_row_number = -1

for i, extra in enumerate(voting_extras):
    extra = extra.strip()

    # alltid 2 §§, alltid ett intevall på max 3 tecken upp till 999. alltid mellanslag 'ersätter'. alltid parti inom parates i slutet.
    correct_syntax = r"^§§\d{1,3}(?:-\d{1,3})?\s+ersätter\s+.+?\s+\([A-Za-zÅÄÖåäö]+\)\s*$"

    if extra_row_number == i:
        continue

    if ',' in extra:
        after_comma = extra.split(',',1)[1].strip()

        if re.match(correct_syntax, after_comma):
            voting_extras_merged.append(extra)
        else:
            merged = extra + ' ' + voting_extras[i+1]
            voting_extras_merged.append(merged)
            extra_row_number = i + 1

    else:
        voting_extras_merged.append(extra)

print(voting_extras_merged)

['Hanna Sandberg (S) ersätter Sedat Arif (S)', 'Nadjam-Ud-Din Malik (S) §§51-55 ersätter Katrin Stjernfeldt Jammeh (S), §§69-73 ersätter Sanna Axelsson (S)', 'Anders Nilsson (S) ersätter Olga Krivtsova (S)', 'Marie Tanndal (S) §§61-73 ersätter Björn Gudmundsson (S) (Vice ordförande)', 'Peter Johansson (S) §§61-73 ersätter Frida Trollmyr (S)', 'Shaip Morina (S) §§64-73 ersätter Bengt-Göran Svensson (S)', 'Ingrid Gunnarson (M) §§51-55 ersätter Nicola Rabi (M), §§58-64 ersätter Malin Ahlström (M)', 'Mats Brogren (M) §§51-55 ersätter Malin Ahlström (M), §§60-73 ersätter Tony Rahm (M)', 'Darko Simic (M) §§65-73 ersätter Malin Ahlström (M)', 'Jenny Bengtsson (SD) ersätter Jörgen Grubb (SD)', 'Stefan Claesson (SD) §§68-73 ersätter Håkan Ask (SD)', 'Marek Lakatos (V) §§51-69 ersätter Anfal Mahdi (V)', 'Tobias Petersson (V) ersätter Showan Shattak (V)', 'Kerstin Håkansson (V) §§51-55 ersätter Carin Gustafsson (V), §§65-73 ersätter Lisa Stolpe (V)', 'Ana Maria Stuparich-Clementi (V) §§70-73 ersätter Anfal Mahdi (V)', 'Anna Ljunggren (MP) §§51-58 ersätter Stefana Hoti (MP), §§63-73 ersätter Mohamed Yassin (MP)', 'Erik Hammarström (MP) §§51-62 ersätter Surra Al Sakban (MP)', 'Eva Bertz (L) §§51-64 ersätter Linda Eklund (L)', 'Joel Laguna Ascacivar (L) §§65-73 ersätter Linda Eklund (L)', 'Martin Molin (C) §§63-73 ersätter Anton Sauer (C)']

In [ ]:
{ 'name': 'Anders Nilsson', 
 'party': 'S', 
 'replacements': [ 
        {
            'replaced_name': 'Shler Bradostin', 
            'paragraphs': [170, ..., 187]
        }, 
        {
            'replaced_name': 'Sedat Arif', 
            'paragraphs': [188, ..., 197]
        }, 
    ], 
}

In [124]:
voting_extras_dict = []

for extra in voting_extras_merged:
    extra, rest = split_first_member(extra)
    extra['replaces'] = []

    rest = rest.split(',')

    for member in rest:
        member = member.split('ersätter')

        paragraph = member[0].strip()
        paragraphs = paragraph_interval(paragraph)

        name = member[1].strip()
        name, rest = split_first_member(name)

        extra['replaces'].append(
            {
                'member': name,
                'paragraphs': paragraphs
            }
        )

    voting_extras_dict.append(extra)

print(voting_extras_dict)

[{'name': 'Hanna Sandberg', 'party': 'S', 'title': None, 'replaces': [{'member': {'name': 'Sedat Arif', 'party': 'S', 'title': None}, 'paragraphs': None}]}, {'name': 'Nadjam-Ud-Din Malik', 'party': 'S', 'title': None, 'replaces': [{'member': {'name': 'Katrin Stjernfeldt Jammeh', 'party': 'S', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55]}, {'member': {'name': 'Sanna Axelsson', 'party': 'S', 'title': None}, 'paragraphs': [69, 70, 71, 72, 73]}]}, {'name': 'Anders Nilsson', 'party': 'S', 'title': None, 'replaces': [{'member': {'name': 'Olga Krivtsova', 'party': 'S', 'title': None}, 'paragraphs': None}]}, {'name': 'Marie Tanndal', 'party': 'S', 'title': None, 'replaces': [{'member': {'name': 'Björn Gudmundsson', 'party': 'S', 'title': 'Vice ordförande'}, 'paragraphs': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Peter Johansson', 'party': 'S', 'title': None, 'replaces': [{'member': {'name': 'Frida Trollmyr', 'party': 'S', 'title': None}, 'paragraphs': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Shaip Morina', 'party': 'S', 'title': None, 'replaces': [{'member': {'name': 'Bengt-Göran Svensson', 'party': 'S', 'title': None}, 'paragraphs': [64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Ingrid Gunnarson', 'party': 'M', 'title': None, 'replaces': [{'member': {'name': 'Nicola Rabi', 'party': 'M', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55]}, {'member': {'name': 'Malin Ahlström', 'party': 'M', 'title': None}, 'paragraphs': [58, 59, 60, 61, 62, 63, 64]}]}, {'name': 'Mats Brogren', 'party': 'M', 'title': None, 'replaces': [{'member': {'name': 'Malin Ahlström', 'party': 'M', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55]}, {'member': {'name': 'Tony Rahm', 'party': 'M', 'title': None}, 'paragraphs': [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Darko Simic', 'party': 'M', 'title': None, 'replaces': [{'member': {'name': 'Malin Ahlström', 'party': 'M', 'title': None}, 'paragraphs': [65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Jenny Bengtsson', 'party': 'SD', 'title': None, 'replaces': [{'member': {'name': 'Jörgen Grubb', 'party': 'SD', 'title': None}, 'paragraphs': None}]}, {'name': 'Stefan Claesson', 'party': 'SD', 'title': None, 'replaces': [{'member': {'name': 'Håkan Ask', 'party': 'SD', 'title': None}, 'paragraphs': [68, 69, 70, 71, 72, 73]}]}, {'name': 'Marek Lakatos', 'party': 'V', 'title': None, 'replaces': [{'member': {'name': 'Anfal Mahdi', 'party': 'V', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]}]}, {'name': 'Tobias Petersson', 'party': 'V', 'title': None, 'replaces': [{'member': {'name': 'Showan Shattak', 'party': 'V', 'title': None}, 'paragraphs': None}]}, {'name': 'Kerstin Håkansson', 'party': 'V', 'title': None, 'replaces': [{'member': {'name': 'Carin Gustafsson', 'party': 'V', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55]}, {'member': {'name': 'Lisa Stolpe', 'party': 'V', 'title': None}, 'paragraphs': [65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Ana Maria Stuparich-Clementi', 'party': 'V', 'title': None, 'replaces': [{'member': {'name': 'Anfal Mahdi', 'party': 'V', 'title': None}, 'paragraphs': [70, 71, 72, 73]}]}, {'name': 'Anna Ljunggren', 'party': 'MP', 'title': None, 'replaces': [{'member': {'name': 'Stefana Hoti', 'party': 'MP', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58]}, {'member': {'name': 'Mohamed Yassin', 'party': 'MP', 'title': None}, 'paragraphs': [63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Erik Hammarström', 'party': 'MP', 'title': None, 'replaces': [{'member': {'name': 'Surra Al Sakban', 'party': 'MP', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]}]}, {'name': 'Eva Bertz', 'party': 'L', 'title': None, 'replaces': [{'member': {'name': 'Linda Eklund', 'party': 'L', 'title': None}, 'paragraphs': [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]}]}, {'name': 'Joel Laguna Ascacivar', 'party': 'L', 'title': None, 'replaces': [{'member': {'name': 'Linda Eklund', 'party': 'L', 'title': None}, 'paragraphs': [65, 66, 67, 68, 69, 70, 71, 72, 73]}]}, {'name': 'Martin Molin', 'party': 'C', 'title': None, 'replaces': [{'member': {'name': 'Anton Sauer', 'party': 'C', 'title': None}, 'paragraphs': [63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73]}]}]